version: 2
updates:
  # ✅ Python dependencies managed by uv
  - package-ecosystem: "uv"
    directory: "/" # Adjust if pyproject.toml is in a subdir
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"

  # 🚫 Ignore all JavaScript dependencies (npm, yarn)
  - package-ecosystem: "npm"
    directory: "/" # Adjust if package.json is in a subdir like /frontend
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"

  # 🚫 Ignore bun if used
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
