version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type:deps"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
    labels:
      - "type:deps"

  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
    labels:
      - "type:deps"
