# Generated by Django 5.2.10 on 2026-03-07 18:01

import django.db.models.deletion
import django.utils.timezone
import modeltrans.fields
import pgtrigger.compiler
import pgtrigger.migrations
import server.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0013_remove_category_color_dark_and_more"),
        ("organizations", "0020_organization_upd_mod_406b4872"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    server.core.models._AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    server.core.models._AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_index=True, help_text="The URL of the external link", unique=True, verbose_name="URL"
                    ),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=("label", "description"), required_languages=(), virtual_fields=True
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Short label for the link (translatable)", max_length=200, verbose_name="Label"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the link (translatable)",
                        verbose_name="Description",
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[("new", "New"), ("review", "Review"), ("work", "Work"), ("done", "Done")],
                        db_index=True,
                        default="new",
                        help_text="Editorial state - links shown only when 'done'",
                        max_length=20,
                        verbose_name="Review Status",
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(
                        blank=True, default="", help_text="Internal reviewer note", verbose_name="Review Comment"
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this link was last checked for accessibility",
                        null=True,
                        verbose_name="Last Checked",
                    ),
                ),
                (
                    "response_code",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Last HTTP response code (e.g., 200, 404)",
                        null=True,
                        verbose_name="Response Code",
                    ),
                ),
                (
                    "failure_count",
                    models.SmallIntegerField(
                        default=0, help_text="Number of consecutive check failures", verbose_name="Failure Count"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Show this link to public users", verbose_name="Public"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this link is active (soft delete)",
                        verbose_name="Active",
                    ),
                ),
                (
                    "link_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of link (e.g., social, website, api, document)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_links",
                        to="categories.category",
                        verbose_name="Link Type",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization that provided this link (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_links",
                        to="organizations.organization",
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Link",
                "verbose_name_plural": "External Links",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(fields=["url"], name="external_li_url_03f04c_idx"),
                    models.Index(fields=["is_active", "is_public"], name="external_li_is_acti_4677ac_idx"),
                    models.Index(fields=["review_status"], name="external_li_review__d026fb_idx"),
                    models.Index(fields=["last_checked"], name="external_li_last_ch_352182_idx"),
                    models.Index(fields=["link_type"], name="external_li_link_ty_ee5e99_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("review_status__in", ["new", "review", "work", "done"])),
                        name="external_links_externallink_review_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("response_code__isnull", True),
                            models.Q(("response_code__gte", 100), ("response_code__lte", 599)),
                            _connector="OR",
                        ),
                        name="external_links_externallink_response_code_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("failure_count__gte", 0)),
                        name="external_links_externallink_failure_count_positive",
                    ),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="externallink",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_1f3c21b1",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="7de0636b740afae8f0af2e5d1533161e3e62343c",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_1f3c21b1_eeb3d",
                    table="external_links_externallink",
                    when="BEFORE",
                ),
            ),
        ),
    ]
