# Generated by Django 5.2.10 on 2026-03-07 18:05

import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_links", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externallink",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("label", "description", "url"), required_languages=(), virtual_fields=True
            ),
        ),
        migrations.AlterField(
            model_name="externallink",
            name="url",
            field=models.URLField(
                db_index=True,
                help_text="The URL of the external link (translatable - defaults to first language)",
                verbose_name="URL",
            ),
        ),
    ]
