# Generated by Django 5.2.10 on 2026-03-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_links", "0002_alter_externallink_i18n_alter_externallink_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="externallink",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique URL identifier (auto-generated from label)",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="externallink",
            name="is_public",
            field=models.BooleanField(
                db_index=True, default=True, help_text="Show this link to public users", verbose_name="Public"
            ),
        ),
    ]
