# Generated by Django 5.2.10 on 2026-03-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_links", "0004_populate_externallink_slugs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externallink",
            name="slug",
        ),
        migrations.AddField(
            model_name="externallink",
            name="identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Short unique identifier (6 characters)",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Identifier",
            ),
        ),
    ]
