# Generated by Django 5.2.10 on 2026-03-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_links", "0007_externallink_identifier_not_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externallink",
            name="identifier",
            field=models.CharField(
                db_index=True,
                help_text="Short unique identifier (6 characters)",
                max_length=10,
                unique=True,
                verbose_name="Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="externallink",
            name="review_status",
            field=models.CharField(
                choices=[("new", "New"), ("review", "Review"), ("work", "Work"), ("done", "Done")],
                db_index=True,
                default="done",
                help_text="Editorial state - links shown only when 'done'",
                max_length=20,
                verbose_name="Review Status",
            ),
        ),
    ]
