# Generated by Django 5.2.10 on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_links", "0008_alter_externallink_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externallink",
            name="is_template",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Auto-detected: True if URL contains placeholders like {osm_type} or {osm_id}",
                verbose_name="Is Template",
            ),
        ),
        migrations.AddField(
            model_name="externallink",
            name="template_vars",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Available template variables and their example values for health check. Example: {'osm_type': 'node', 'osm_id': '123456', 'source_id': 'node/123456'}",
                verbose_name="Template Variables",
            ),
        ),
        migrations.AddField(
            model_name="externallink",
            name="run_health_check",
            field=models.BooleanField(
                default=True,
                help_text="Whether to run health checks on this link. Disable for templates without example values.",
                verbose_name="Run Health Check",
            ),
        ),
    ]
