[tool.poetry]
name = "wodore"
description = "Wodore Backend"
version = "0.1.0"
readme = "README.md"
authors = ["tb <tb@wodore.com>"]
packages = [{"include"= "server"}]


[tool.poetry.dependencies]
python = "^3.10"

django = { version = "^4.2", extras = ["argon2"] }
django-split-settings = "^1.2"
django-axes = "^5.41"
django-csp = "^3.7"
django-health-check = "^3.16"
django-http-referrer-policy = "^1.1"
django-permissions-policy = "^4.14"
django-stubs-ext = "^4.2"
django-ninja = "^1.0"

psycopg2-binary = "^2.9"
gunicorn = "^20.0"
python-decouple = "^3.8"
structlog = "^23.1"
django-colorfield = "^0.8.0"
pillow = "^9.5.0"
django-model-utils = "^4.3.1"
django-jsoneditor = "^0.2.4"
django-modeltrans = "^0.7.4"
django-jsonform = "^2.17.1"
msgspec = "^0.18.4"


[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^4.1"
django-querycount = "^0.8"
django-migration-linter = "^4.1"
django-extra-checks = "^0.13"
nplusone = "^1.0"

wemake-python-styleguide = "^0.17"
flake8-pytest-style = "^1.7"
flake8-django = "^1.2"
flake8-logging-format = "^0.9"
nitpick = "^0.33"
doc8 = "^1.0"

pytest = "^7.3"
pytest-django = "^4.5"
pytest-cov = "^4.0"
django-coverage-plugin = "^3.0"
pytest-randomly = "^3.12"
pytest-timeout = "^2.1"
django-test-migrations = "^1.3"
hypothesis = "^6.75"

mypy = "^1.3"
django-stubs = "^4.2"

djlint = "^1.27"
yamllint = "^1.31"
safety = "^2.3"
dotenv-linter = "^0.4"
polint = "^0.4"
dennis = "^1.1"
dump-env = "^1.3"
ipython = "^8.13"
icecream = "^2.1.3"

[tool.poetry.scripts]
manage = 'manage:main'

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^7.0"
sphinx-autodoc-typehints = "^1.23"
tomli = "^2.0"


[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"


[tool.djlint]
ignore = "H006,H030,H031"
include = "H017,H035"
indent = 2
blank_line_after_tag = "load,extends"
profile = "django"
max_line_length = 80
format_attribute_template_tags = true


[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/0.17.0/styles/nitpick-style-wemake.toml"
