# Generated by Django 6.0.3 on 2026-09-26 19:21

import django.utils.timezone
import server.apps.accounts.managers
from django.db import migrations, models


def copy_auth_users(apps, schema_editor):
    """Carry existing auth.User rows over, primary keys preserved.

    Email becomes COALESCE(NULLIF(email, ''), username) — legacy
    Zitadel-synced accounts have emails; fixture users have username=email.
    Password hashes are copied verbatim (still verifiable). Runs on fresh
    databases too, where auth_user is empty (no-op).

    The old table is read via raw SQL: the swapped-out auth.User historical
    model has no default manager once AUTH_USER_MODEL points elsewhere.
    """
    from django.db import connections

    alias = schema_editor.connection.alias
    NewUser = apps.get_model("accounts", "User")
    if NewUser.objects.using(alias).exists():
        return  # idempotence guard for re-runs

    # Fresh databases never create auth_user (the swapped-out model's
    # CreateModel is skipped) - nothing to copy there.
    table_names = set(schema_editor.connection.introspection.table_names())
    if "auth_user" not in table_names:
        return

    user_rows, group_rows, perm_rows = [], [], []
    with connections[alias].cursor() as cursor:
        cursor.execute(
            "SELECT id, password, last_login, is_superuser, first_name, "
            "last_name, is_staff, is_active, date_joined, email, username "
            "FROM auth_user ORDER BY id"
        )
        user_rows = cursor.fetchall()
        if user_rows:
            cursor.execute("SELECT user_id, group_id FROM auth_user_groups")
            group_rows = cursor.fetchall()
            cursor.execute(
                "SELECT user_id, permission_id "
                "FROM auth_user_user_permissions"
            )
            perm_rows = cursor.fetchall()

    seen_emails: set[str] = set()
    new_users = []
    for row in user_rows:
        (pk, password, last_login, is_superuser, first_name, last_name,
         is_staff, is_active, date_joined, email, username) = row
        email = (email or username or "").strip()
        if not email:
            email = f"unknown-{pk}@invalid.local"
        if email in seen_emails:
            continue  # duplicate email: first one wins (dev data hygiene)
        seen_emails.add(email)
        new_users.append(NewUser(
            pk=pk, password=password, last_login=last_login,
            is_superuser=is_superuser, first_name=first_name,
            last_name=last_name, is_staff=is_staff, is_active=is_active,
            date_joined=date_joined, email=email,
        ))
    if not new_users:
        return
    NewUser.objects.using(alias).bulk_create(new_users)

    groups_through = NewUser.groups.through._meta.db_table
    perms_through = NewUser.user_permissions.through._meta.db_table
    with connections[alias].cursor() as cursor:
        if group_rows:
            cursor.executemany(
                f"INSERT INTO {groups_through} (user_id, group_id) VALUES (%s, %s)",
                group_rows,
            )
        if perm_rows:
            cursor.executemany(
                f"INSERT INTO {perms_through} (user_id, permission_id) "
                "VALUES (%s, %s)",
                perm_rows,
            )


def uncopy_auth_users(apps, schema_editor):
    NewUser = apps.get_model("accounts", "User")
    NewUser.objects.using(schema_editor.connection.alias).all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', server.apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.RunPython(copy_auth_users, uncopy_auth_users),
    ]
