# Generated by Django 5.2.9 on 2025-12-31 19:32

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("huts", "0040_alter_hut_open_monthly_alter_huttype_symbol_and_more"),
        ("organizations", "0018_alter_organization_color_dark_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HutAvailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="Hut ID in the source organization's system", max_length=100, verbose_name="Source ID"
                    ),
                ),
                (
                    "availability_date",
                    models.DateField(
                        db_index=True,
                        help_text="Date for which this availability data applies",
                        verbose_name="Availability Date",
                    ),
                ),
                (
                    "free",
                    models.PositiveSmallIntegerField(
                        help_text="Number of available places", verbose_name="Free Places"
                    ),
                ),
                (
                    "total",
                    models.PositiveSmallIntegerField(help_text="Total number of places", verbose_name="Total Places"),
                ),
                (
                    "occupancy_percent",
                    models.FloatField(help_text="Occupancy percentage (0-100)", verbose_name="Occupancy Percent"),
                ),
                (
                    "occupancy_steps",
                    models.PositiveSmallIntegerField(
                        help_text="Occupancy in discrete steps (0-100, increments of 10)",
                        verbose_name="Occupancy Steps",
                    ),
                ),
                (
                    "occupancy_status",
                    models.CharField(
                        help_text="Status: empty, low, medium, high, full, unknown",
                        max_length=20,
                        verbose_name="Occupancy Status",
                    ),
                ),
                (
                    "reservation_status",
                    models.CharField(
                        help_text="Status: unknown, possible, not_possible, not_online",
                        max_length=20,
                        verbose_name="Reservation Status",
                    ),
                ),
                ("link", models.URLField(blank=True, default="", max_length=500, verbose_name="Booking Link")),
                (
                    "first_checked",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this availability was first recorded",
                        verbose_name="First Checked",
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        db_index=True, help_text="When this hut was last queried", verbose_name="Last Checked"
                    ),
                ),
                (
                    "hut",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="huts.hut",
                        verbose_name="Hut",
                    ),
                ),
                (
                    "hut_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hut type on this date (open/closed)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="availabilities",
                        to="huts.huttype",
                        verbose_name="Hut Type",
                    ),
                ),
                (
                    "source_organization",
                    models.ForeignKey(
                        db_index=False,
                        help_text="Organization providing the booking data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hut_availabilities",
                        to="organizations.organization",
                        verbose_name="Source Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hut Availability",
                "verbose_name_plural": "Hut Availabilities",
                "ordering": ("availability_date", "hut__name"),
            },
        ),
        migrations.CreateModel(
            name="HutAvailabilityHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "availability_date",
                    models.DateField(
                        db_index=True,
                        help_text="Target date this availability applies to",
                        verbose_name="Availability Date",
                    ),
                ),
                ("free", models.PositiveSmallIntegerField(verbose_name="Free Places")),
                ("total", models.PositiveSmallIntegerField(verbose_name="Total Places")),
                ("occupancy_percent", models.FloatField(verbose_name="Occupancy Percent")),
                (
                    "occupancy_status",
                    models.CharField(
                        help_text="Status: empty, low, medium, high, full, unknown",
                        max_length=20,
                        verbose_name="Occupancy Status",
                    ),
                ),
                (
                    "reservation_status",
                    models.CharField(
                        help_text="Status: unknown, possible, not_possible, not_online",
                        max_length=20,
                        verbose_name="Reservation Status",
                    ),
                ),
                (
                    "first_checked",
                    models.DateTimeField(
                        db_index=True, help_text="When this state was first observed", verbose_name="First Checked"
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        help_text="When this state was last confirmed (updated on every check)",
                        verbose_name="Last Checked",
                    ),
                ),
                (
                    "availability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="availability.hutavailability",
                        verbose_name="Availability",
                    ),
                ),
                (
                    "hut",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_history",
                        to="huts.hut",
                        verbose_name="Hut",
                    ),
                ),
                (
                    "hut_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hut type on this date (open/closed)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="availability_history",
                        to="huts.huttype",
                        verbose_name="Hut Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hut Availability History",
                "verbose_name_plural": "Hut Availability Histories",
                "ordering": ("-first_checked",),
            },
        ),
        migrations.AddIndex(
            model_name="hutavailability",
            index=models.Index(fields=["hut", "availability_date"], name="availabilit_hut_id_3f0736_idx"),
        ),
        migrations.AddIndex(
            model_name="hutavailability",
            index=models.Index(
                fields=["source_organization", "availability_date"], name="availabilit_source__75cea1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hutavailability",
            index=models.Index(fields=["availability_date", "last_checked"], name="availabilit_availab_e8d9f2_idx"),
        ),
        migrations.AddConstraint(
            model_name="hutavailability",
            constraint=models.UniqueConstraint(fields=("hut", "availability_date"), name="unique_hut_date"),
        ),
        migrations.AddIndex(
            model_name="hutavailabilityhistory",
            index=models.Index(
                fields=["hut", "availability_date", "first_checked"], name="availabilit_hut_id_d208bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hutavailabilityhistory",
            index=models.Index(fields=["availability_date", "first_checked"], name="availabilit_availab_77d3b9_idx"),
        ),
    ]
