# Generated by Django 5.2.9 on 2025-12-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hutavailability",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Inactive huts are updated with low priority only",
                verbose_name="Is Active",
            ),
        ),
    ]
