# Generated by Django 5.2.9 on 2025-12-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0002_hutavailability_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hutavailability",
            name="is_active",
        ),
    ]
