# Generated by Django 5.2.9 on 2025-12-31 21:12

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0003_remove_hutavailability_is_active"),
        ("huts", "0041_hut_availability_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityStatus",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "hut",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="availability_status",
                        serialize=False,
                        to="huts.hut",
                        verbose_name="Hut",
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When availability was last fetched for this hut",
                        verbose_name="Last Checked",
                    ),
                ),
                (
                    "last_success",
                    models.DateTimeField(
                        blank=True,
                        help_text="When availability data was last successfully retrieved",
                        null=True,
                        verbose_name="Last Successful Fetch",
                    ),
                ),
                (
                    "has_data",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this hut has ever returned availability data",
                        verbose_name="Has Availability Data",
                    ),
                ),
                (
                    "consecutive_failures",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of consecutive times the fetch returned no data or failed",
                        verbose_name="Consecutive Failures",
                    ),
                ),
            ],
            options={
                "verbose_name": "Availability Status",
                "verbose_name_plural": "Availability Statuses",
                "ordering": ("-last_checked",),
            },
        ),
    ]
