# Generated by Django 5.2.9 on 2026-01-04 16:36

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0005_alter_availabilitystatus_created_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="availabilitystatus",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_b0bf06b7",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="0e7d2d0e92b7aab8479116f74f1d8425add248ff",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_b0bf06b7_0b29d",
                    table="availability_availabilitystatus",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hutavailability",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_4ebc86d7",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="ca8aae625f442584a6b7275f9a2aab46e3e18ddf",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_4ebc86d7_75d50",
                    table="availability_hutavailability",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hutavailabilityhistory",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_93a0cf52",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="2ed5afabeaee5c7965076bef7b37f7543e9e96d3",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_93a0cf52_1a919",
                    table="availability_hutavailabilityhistory",
                    when="BEFORE",
                ),
            ),
        ),
    ]
