# Generated by Django 5.2.9 on 2026-01-04 17:01

from django.db import migrations


def fix_source_id_forward(apps, schema_editor):
    """
    Fix source_id values in HutAvailability and HutAvailabilityHistory tables.

    The source_id field should contain the external organization's ID for the hut
    (from HutOrganizationAssociation.source_id), not the Wodore internal hut ID.

    This migration corrects existing data that was incorrectly using hut.id instead
    of the actual source organization's ID.
    """
    HutAvailability = apps.get_model("availability", "HutAvailability")
    HutAvailabilityHistory = apps.get_model("availability", "HutAvailabilityHistory")
    HutOrganizationAssociation = apps.get_model("huts", "HutOrganizationAssociation")

    # Build a mapping of (hut_id, source_org_id) -> correct_source_id
    source_id_mapping = {}
    for assoc in HutOrganizationAssociation.objects.select_related('hut', 'organization'):
        if assoc.source_id:
            key = (assoc.hut_id, assoc.organization_id)
            source_id_mapping[key] = str(assoc.source_id)

    # Update HutAvailability records
    availability_updates = []
    for avail in HutAvailability.objects.select_related('hut', 'source_organization').iterator(chunk_size=1000):
        key = (avail.hut_id, avail.source_organization_id)
        correct_source_id = source_id_mapping.get(key)

        if correct_source_id and avail.source_id != correct_source_id:
            avail.source_id = correct_source_id
            availability_updates.append(avail)

            # Bulk update every 500 records to avoid memory issues
            if len(availability_updates) >= 500:
                HutAvailability.objects.bulk_update(availability_updates, ['source_id'])
                availability_updates = []

    # Final bulk update for remaining records
    if availability_updates:
        HutAvailability.objects.bulk_update(availability_updates, ['source_id'])

    # Update HutAvailabilityHistory records
    history_updates = []
    for history in HutAvailabilityHistory.objects.select_related('availability').iterator(chunk_size=1000):
        if history.availability:
            # Get the correct source_id from the availability record (which we just fixed)
            correct_source_id = history.availability.source_id

            # History doesn't have source_id field, so we skip this table
            # The history table doesn't store source_id, only references availability
            pass

    print(f"Fixed source_id for availability records")


def fix_source_id_reverse(apps, schema_editor):
    """
    Reverse migration - no action needed.

    We cannot reverse this migration because we don't have the incorrect values stored.
    The data was wrong before, so reverting would require re-breaking it, which doesn't
    make sense.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0006_availabilitystatus_upd_mod_b0bf06b7_and_more"),
        ("huts", "0015_alter_hutorganizationassociation_hut"),  # Need this for HutOrganizationAssociation
    ]

    operations = [
        migrations.RunPython(fix_source_id_forward, fix_source_id_reverse),
    ]
