# Generated by Django 5.2.9 on 2026-01-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0007_fix_source_id_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hutavailability",
            name="source_id",
            field=models.CharField(
                help_text="Hut ID in the source organization's system", max_length=50, verbose_name="Source ID"
            ),
        ),
    ]
