# Generated by Django 5.2.10 on 2026-01-10 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0008_alter_hutavailability_source_id"),
        ("categories", "0003_rename_symbol_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hutavailability",
            name="hut_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Hut type on this date (open/closed)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="availabilities",
                to="categories.category",
                verbose_name="Hut Type",
            ),
        ),
        migrations.AlterField(
            model_name="hutavailabilityhistory",
            name="hut_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Hut type on this date (open/closed)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="availability_history",
                to="categories.category",
                verbose_name="Hut Type",
            ),
        ),
    ]
