# Generated by Django 6.0.3 on 2026-09-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0009_alter_hutavailability_hut_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hutavailability",
            name="free",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of available places (null = not published by source)",
                null=True,
                verbose_name="Free Places",
            ),
        ),
        migrations.AlterField(
            model_name="hutavailability",
            name="occupancy_percent",
            field=models.FloatField(
                blank=True,
                help_text="Occupancy percentage (0-100), null if not computable",
                null=True,
                verbose_name="Occupancy Percent",
            ),
        ),
        migrations.AlterField(
            model_name="hutavailability",
            name="occupancy_status",
            field=models.CharField(
                help_text="Status: empty, low, medium, high, full, free_unknown, unknown",
                max_length=20,
                verbose_name="Occupancy Status",
            ),
        ),
        migrations.AlterField(
            model_name="hutavailability",
            name="occupancy_steps",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Occupancy in discrete steps (0-100, increments of 10)",
                null=True,
                verbose_name="Occupancy Steps",
            ),
        ),
        migrations.AlterField(
            model_name="hutavailability",
            name="total",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Total number of places (null = not published by source)",
                null=True,
                verbose_name="Total Places",
            ),
        ),
        migrations.AlterField(
            model_name="hutavailabilityhistory",
            name="free",
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name="Free Places"
            ),
        ),
        migrations.AlterField(
            model_name="hutavailabilityhistory",
            name="occupancy_percent",
            field=models.FloatField(null=True, verbose_name="Occupancy Percent"),
        ),
        migrations.AlterField(
            model_name="hutavailabilityhistory",
            name="occupancy_status",
            field=models.CharField(
                help_text="Status: empty, low, medium, high, full, free_unknown, unknown",
                max_length=20,
                verbose_name="Occupancy Status",
            ),
        ),
        migrations.AlterField(
            model_name="hutavailabilityhistory",
            name="total",
            field=models.PositiveSmallIntegerField(
                null=True, verbose_name="Total Places"
            ),
        ),
    ]
