# Generated by Django 6.0.3 on 2026-09-21 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0010_alter_hutavailability_free_and_more"),
        ("categories", "0015_category_categories__parent__91c7d9_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hutavailability",
            name="hut_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Hut type on this date (open/closed)",
                limit_choices_to=models.Q(("parent__slug", "accommodation")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="availabilities",
                to="categories.category",
                verbose_name="Hut Type",
            ),
        ),
        migrations.AlterField(
            model_name="hutavailabilityhistory",
            name="hut_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Hut type on this date (open/closed)",
                limit_choices_to=models.Q(("parent__slug", "accommodation")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="availability_history",
                to="categories.category",
                verbose_name="Hut Type",
            ),
        ),
    ]
