# Generated by Django 6.0.3 on 2026-09-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0011_alter_hutavailability_hut_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hutavailability',
            name='occupancy_status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('free_unknown', 'free_unknown'), ('empty', 'empty'), ('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('full', 'full')], help_text='Status: empty, low, medium, high, full, free_unknown, unknown', max_length=20, verbose_name='Occupancy Status'),
        ),
        migrations.AlterField(
            model_name='hutavailability',
            name='reservation_status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('possible', 'possible'), ('not_possible', 'not_possible'), ('not_online', 'not_online')], help_text='Status: unknown, possible, not_possible, not_online', max_length=20, verbose_name='Reservation Status'),
        ),
        migrations.AlterField(
            model_name='hutavailabilityhistory',
            name='occupancy_status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('free_unknown', 'free_unknown'), ('empty', 'empty'), ('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('full', 'full')], help_text='Status: empty, low, medium, high, full, free_unknown, unknown', max_length=20, verbose_name='Occupancy Status'),
        ),
        migrations.AlterField(
            model_name='hutavailabilityhistory',
            name='reservation_status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('possible', 'possible'), ('not_possible', 'not_possible'), ('not_online', 'not_online')], help_text='Status: unknown, possible, not_possible, not_online', max_length=20, verbose_name='Reservation Status'),
        ),
    ]
