# Generated by Django 6.0.3 on 2026-09-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0012_alter_hutavailability_occupancy_status_and_more"),
        ("categories", "0015_category_categories__parent__91c7d9_idx"),
        ("huts", "0059_alter_hut_hut_type_closed_alter_hut_hut_type_open"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="hutavailabilityhistory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "occupancy_status__in",
                        [
                            "unknown",
                            "free_unknown",
                            "empty",
                            "low",
                            "medium",
                            "high",
                            "full",
                        ],
                    )
                ),
                name="availability_hutavailabilityhistory_occupancy_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="hutavailabilityhistory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "reservation_status__in",
                        ["unknown", "possible", "not_possible", "not_online"],
                    )
                ),
                name="availability_hutavailabilityhistory_reservation_status_valid",
            ),
        ),
    ]
