# Generated by Django 6.0.3 on 2026-09-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0014_hutavailability_availability_hutavailability_occupancy_status_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hutavailability',
            name='free_tolerance',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Plus/minus uncertainty on free places (0 = exact, null = unknown); estimated sources report free ± tolerance', null=True, verbose_name='Free Places Tolerance'),
        ),
        migrations.AddField(
            model_name='hutavailabilityhistory',
            name='free_tolerance',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Free Places Tolerance'),
        ),
    ]
