# Generated by Django 5.2.10 on 2026-01-12 12:07

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import modeltrans.fields
import pgtrigger.compiler
import pgtrigger.migrations
import server.core.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("licenses", "0006_license_upd_mod_26a7a6c1"),
        ("organizations", "0020_organization_upd_mod_406b4872"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "created",
                    server.core.models._AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    server.core.models._AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("i18n", modeltrans.fields.TranslationField(fields=(), required_languages=(), virtual_fields=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("slug", models.SlugField(help_text="Symbol identifier (e.g., 'water', 'mountain')", max_length=100)),
                (
                    "style",
                    models.CharField(
                        choices=[("detailed", "Detailed"), ("simple", "Simple"), ("mono", "Monochrome")],
                        db_index=True,
                        default="detailed",
                        help_text="Symbol style variant",
                        max_length=10,
                        verbose_name="Style",
                    ),
                ),
                (
                    "svg_file",
                    models.FileField(
                        help_text="SVG file for this symbol", upload_to="symbols/", verbose_name="SVG File"
                    ),
                ),
                (
                    "search_text",
                    models.CharField(
                        blank=True,
                        help_text="Keywords for admin search (e.g., 'water, river, lake, blue')",
                        max_length=200,
                        verbose_name="Search Text",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Only shown to admin if not active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("disabled", "Disabled"),
                            ("rejected", "Rejected"),
                        ],
                        default="approved",
                        max_length=12,
                        verbose_name="Review status",
                    ),
                ),
                ("review_comment", models.TextField(blank=True, default="", verbose_name="Review Comment")),
                ("author", models.CharField(blank=True, default="", max_length=255, null=True, verbose_name="Author")),
                (
                    "author_url",
                    models.URLField(blank=True, default="", max_length=500, null=True, verbose_name="Author URL"),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, default="", max_length=500, null=True, verbose_name="Source URL"),
                ),
                (
                    "source_ident",
                    models.CharField(
                        blank=True, default="", max_length=512, null=True, verbose_name="Source Identification"
                    ),
                ),
                (
                    "uploaded_by_anonym",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="E-mail or name of the anonymous uploader",
                        max_length=255,
                        null=True,
                        verbose_name="Uploaded By (Anonym)",
                    ),
                ),
                (
                    "uploaded_date",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="svg_file", verbose_name="Uploaded Date"
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="licenses.license", verbose_name="License"
                    ),
                ),
                (
                    "source_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.organization",
                        verbose_name="Source Organization",
                    ),
                ),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="symbol_uploaded_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By (User)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Symbol",
                "verbose_name_plural": "Symbols",
                "ordering": ("slug", "style"),
                "indexes": [
                    models.Index(fields=["slug", "style"], name="symbols_sym_slug_ab9858_idx"),
                    models.Index(fields=["is_active", "slug"], name="symbols_sym_is_acti_407add_idx"),
                    django.contrib.postgres.indexes.GinIndex(fields=["i18n"], name="symbols_sym_i18n_fb8983_gin"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("slug", "style"), name="symbols_symbol_slug_style_unique"),
                    models.CheckConstraint(
                        condition=models.Q(("review_status__in", ["pending", "approved", "disabled", "rejected"])),
                        name="symbols_symbol_review_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("style__in", ["detailed", "simple", "mono"])),
                        name="symbols_symbol_style_valid",
                    ),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="symbol",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_9acd72d3",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="e9ab1c79dd6a781473571c6e353ba62a19ad4d90",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_9acd72d3_f254d",
                    table="symbols_symbol",
                    when="BEFORE",
                ),
            ),
        ),
    ]
