# Generated by Django 5.2.10 on 2026-01-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("symbols", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="symbol",
            name="symbols_sym_i18n_fb8983_gin",
        ),
        migrations.RemoveField(
            model_name="symbol",
            name="i18n",
        ),
    ]
