# Generated by Django 5.2.10 on 2026-01-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("symbols", "0002_remove_symbol_symbols_sym_i18n_fb8983_gin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SymbolGroup",
            fields=[],
            options={
                "verbose_name": "Symbol Group",
                "verbose_name_plural": "Symbol Groups",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("symbols.symbol",),
        ),
    ]
