# Generated by Django 5.2.10 on 2026-01-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("symbols", "0003_symbolgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symbol",
            name="style",
            field=models.CharField(
                choices=[("detailed", "detailed"), ("simple", "simple"), ("mono", "mono")],
                db_index=True,
                default="detailed",
                help_text="Symbol style variant",
                max_length=10,
                verbose_name="Style",
            ),
        ),
    ]
