# Generated by Django 5.2.10 on 2026-01-19 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0006_license_upd_mod_26a7a6c1"),
        ("organizations", "0020_organization_upd_mod_406b4872"),
        ("symbols", "0004_alter_symbol_style"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="symbol",
            name="symbols_symbol_style_valid",
        ),
        migrations.AlterField(
            model_name="symbol",
            name="style",
            field=models.CharField(
                choices=[
                    ("detailed", "detailed"),
                    ("simple", "simple"),
                    ("mono", "mono"),
                    ("outlined", "outlined"),
                    ("filled", "filled"),
                    ("detailed-animated", "detailed-animated"),
                    ("simple-animated", "simple-animated"),
                    ("mono-animated", "mono-animated"),
                    ("outlined-animated", "outlined-animated"),
                    ("filled-animated", "filled-animated"),
                ],
                db_index=True,
                default="detailed",
                help_text="Symbol style variant",
                max_length=20,
                verbose_name="Style",
            ),
        ),
        migrations.AddConstraint(
            model_name="symbol",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "style__in",
                        [
                            "detailed",
                            "simple",
                            "mono",
                            "outlined",
                            "filled",
                            "detailed-animated",
                            "simple-animated",
                            "mono-animated",
                            "outlined-animated",
                            "filled-animated",
                        ],
                    )
                ),
                name="symbols_symbol_style_valid",
            ),
        ),
    ]
