# Generated by Django 6.1.1 on 2026-10-08 11:25

import django.db.models.deletion
import django.utils.timezone
import modeltrans.fields
import pgtrigger.compiler
import pgtrigger.migrations
import server.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0017_category_seo_sitemap'),
        ('organizations', '0020_organization_upd_mod_406b4872'),
        ('symbols', '0007_fix_style_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', server.core.models._AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', server.core.models._AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('i18n', modeltrans.fields.TranslationField(fields=(), required_languages=(), virtual_fields=True)),
                ('slug', models.SlugField(help_text='Unique identifier for this icon pack', max_length=100, unique=True, verbose_name='Slug')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON. Import commands record their pinned upstream refs here.', verbose_name='Extra Metadata')),
                ('source_org', models.ForeignKey(help_text='Organization providing this icon pack', on_delete=django.db.models.deletion.CASCADE, related_name='symbol_collections', to='organizations.organization', verbose_name='Source Organization')),
            ],
            options={
                'verbose_name': 'Symbol Collection',
                'verbose_name_plural': 'Symbol Collections',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', server.core.models._AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', server.core.models._AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('i18n', modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
                ('slug', models.SlugField(help_text='Upstream icon identifier, unique within the pack', max_length=100, verbose_name='Slug')),
                ('name', models.CharField(blank=True, default='', help_text='Display name (English source; translated via i18n)', max_length=200, verbose_name='Name')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Display order (lower values appear first)', verbose_name='Order')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only shown to admin if not active', verbose_name='Active')),
                ('unicode', models.CharField(blank=True, db_index=True, help_text="Unicode hexcode(s), variation selectors stripped (e.g. '26FA' or '1F468-200D-2764')", max_length=64, null=True, verbose_name='Unicode')),
                ('category', models.ForeignKey(blank=True, help_text='CLDR subgroup category (non-root)', limit_choices_to=models.Q(('parent__isnull', False)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icons', to='categories.category', verbose_name='Category')),
                ('symbol_detailed', models.ForeignKey(blank=True, help_text='Reference to detailed symbol from Symbols app', limit_choices_to={'style': 'detailed'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icons_detailed', to='symbols.symbol', verbose_name='Symbol (Detailed)')),
                ('symbol_mono', models.ForeignKey(blank=True, help_text='Reference to monochrome symbol from Symbols app', limit_choices_to={'style': 'mono'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icons_mono', to='symbols.symbol', verbose_name='Symbol (Mono)')),
                ('symbol_simple', models.ForeignKey(blank=True, help_text='Reference to simple symbol from Symbols app', limit_choices_to={'style': 'simple'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icons_simple', to='symbols.symbol', verbose_name='Symbol (Simple)')),
                ('pack', models.ForeignKey(help_text='Icon pack this icon belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='icons', to='symbols.symbolcollection', verbose_name='Pack')),
            ],
            options={
                'verbose_name': 'Icon',
                'verbose_name_plural': 'Icons',
                'ordering': ('pack__slug', 'order', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='IconKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', server.core.models._AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', server.core.models._AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('locale', models.CharField(db_index=True, help_text='Language code of this keyword (de, en, fr, it)', max_length=8, verbose_name='Locale')),
                ('keyword', models.CharField(help_text='Original keyword form (label or tag)', max_length=200, verbose_name='Keyword')),
                ('keyword_folded', models.CharField(help_text='Accent- and case-folded form used for matching', max_length=200, verbose_name='Keyword (folded)')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='symbols.icon', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Icon Keyword',
                'verbose_name_plural': 'Icon Keywords',
                'ordering': ('icon', 'locale', 'keyword_folded'),
                'indexes': [models.Index(fields=['locale', 'keyword_folded'], name='symbols_ico_locale_07599f_idx')],
                'constraints': [models.UniqueConstraint(fields=('icon', 'locale', 'keyword_folded'), name='symbols_iconkeyword_icon_locale_folded_unique')],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='iconkeyword',
            trigger=pgtrigger.compiler.Trigger(name='upd_mod_8d517cd2', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.modified = NOW(); RETURN NEW;', hash='0c4f70df9f4acf167bf3db6f4a941f3f899bcdd8', operation='UPDATE', pgid='pgtrigger_upd_mod_8d517cd2_cad00', table='symbols_iconkeyword', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='symbolcollection',
            trigger=pgtrigger.compiler.Trigger(name='upd_mod_c3612658', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.modified = NOW(); RETURN NEW;', hash='f50aacff6cf725a713d7f434d2d09660e1d15bce', operation='UPDATE', pgid='pgtrigger_upd_mod_c3612658_6b1a6', table='symbols_symbolcollection', when='BEFORE')),
        ),
        migrations.AddIndex(
            model_name='icon',
            index=models.Index(fields=['pack', 'order', 'slug'], name='symbols_ico_pack_id_82aa6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='icon',
            constraint=models.UniqueConstraint(fields=('pack', 'slug'), name='symbols_icon_pack_slug_unique'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='icon',
            trigger=pgtrigger.compiler.Trigger(name='upd_mod_ae812fd4', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.modified = NOW(); RETURN NEW;', hash='208cce7fb11a2ace1859c6e26ee6051254243ea3', operation='UPDATE', pgid='pgtrigger_upd_mod_ae812fd4_52538', table='symbols_icon', when='BEFORE')),
        ),
    ]
