# Generated by Django 6.1.1 on 2026-10-08 16:05

import django.db.models.deletion
import django.utils.timezone
import modeltrans.fields
import pgtrigger.compiler
import pgtrigger.migrations
import server.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0008_symbolcollection_icon_iconkeyword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconCuratedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', server.core.models._AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', server.core.models._AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('i18n', modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
                ('slug', models.SlugField(help_text="List identifier requested by clients (e.g. 'activities')", max_length=100, unique=True, verbose_name='Slug')),
                ('name', models.CharField(blank=True, default='', help_text='Display name (English source; translated via i18n)', max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Icon Curated List',
                'verbose_name_plural': 'Icon Curated Lists',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='IconCuratedListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', server.core.models._AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', server.core.models._AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('curated_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='symbols.iconcuratedlist', verbose_name='Curated list')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curated_list_entries', to='symbols.icon', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Icon Curated List Entry',
                'verbose_name_plural': 'Icon Curated List Entries',
                'ordering': ('curated_list', 'icon__order', 'icon__slug'),
            },
        ),
        migrations.AddField(
            model_name='iconcuratedlist',
            name='icons',
            field=models.ManyToManyField(blank=True, help_text='Curated icons, managed in the admin', related_name='curated_lists', through='symbols.IconCuratedListEntry', to='symbols.icon', verbose_name='Icons'),
        ),
        migrations.AddConstraint(
            model_name='iconcuratedlistentry',
            constraint=models.UniqueConstraint(fields=('curated_list', 'icon'), name='symbols_iconcuratedlistentry_list_icon_unique'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='iconcuratedlistentry',
            trigger=pgtrigger.compiler.Trigger(name='upd_mod_eb21d3ab', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.modified = NOW(); RETURN NEW;', hash='72fc5edc0e54e4c490a7ae0c84afe87d66385086', operation='UPDATE', pgid='pgtrigger_upd_mod_eb21d3ab_6d395', table='symbols_iconcuratedlistentry', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='iconcuratedlist',
            trigger=pgtrigger.compiler.Trigger(name='upd_mod_2d8037ba', sql=pgtrigger.compiler.UpsertTriggerSql(func='NEW.modified = NOW(); RETURN NEW;', hash='86de3a70512064a8058c9b3761dc1a6ffc3f812f', operation='UPDATE', pgid='pgtrigger_upd_mod_2d8037ba_9f3fe', table='symbols_iconcuratedlist', when='BEFORE')),
        ),
    ]
