# Generated by Django 6.1.1 on 2026-10-10 22:11

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    """Trigram GIN index for the /v1/icons ranked search.

    ``gin_trgm_ops`` serves the endpoint's leading-wildcard
    ``keyword_folded__contains`` scans (mirrors the hut/geoplace name
    indexes). The extension op is IF NOT EXISTS — mirrors
    huts.0049_add_search_extensions, and keeps fresh databases working
    regardless of app migration ordering.
    """

    dependencies = [
        ('symbols', '0010_seed_activities_list'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='iconkeyword',
            index=django.contrib.postgres.indexes.GinIndex(fields=['keyword_folded'], name='iconkeyword_folded_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
