# Generated by Django 5.0 on 2023-12-12 21:29

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import model_utils.fields
import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=("name", "note"), required_languages=(), virtual_fields=True
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="For example 'SAC Bern', 'Naturschutzverein Hergiswil', ...",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                ("url", models.URLField(blank=True, default="", verbose_name="URL")),
                ("note", models.TextField(blank=True, default="", max_length=500, verbose_name="Note")),
            ],
            options={
                "verbose_name": "Owner",
                "ordering": (django.db.models.functions.text.Lower("name_i18n"),),
            },
        ),
        migrations.CreateModel(
            name="OwnerContactAssociation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name="Order")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_details",
                        to="contacts.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="owners.owner", verbose_name="Owner"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacts to Owner",
                "ordering": ("contact__function__priority", "order", "owner__name"),
                "unique_together": {("contact", "owner")},
            },
        ),
        migrations.AddField(
            model_name="owner",
            name="contacts",
            field=models.ManyToManyField(
                null=True,
                related_name="owner",
                through="owners.OwnerContactAssociation",
                to="contacts.contact",
                verbose_name="Contacts",
            ),
        ),
        migrations.AddIndex(
            model_name="owner",
            index=django.contrib.postgres.indexes.GinIndex(fields=["i18n"], name="owners_owne_i18n_3ae03d_gin"),
        ),
    ]
