# Generated by Django 5.0 on 2023-12-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("owners", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ownercontactassociation",
            options={
                "ordering": ("contact__function__priority", "order", "owner__name"),
                "verbose_name": "Owner and Contact Association",
            },
        ),
        migrations.AlterUniqueTogether(
            name="ownercontactassociation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="ownercontactassociation",
            constraint=models.UniqueConstraint(
                fields=("contact", "owner"), name="owners_ownercontactassociation_unique_relationships"
            ),
        ),
    ]
