# Generated by Django 5.0 on 2023-12-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("owners", "0002_alter_ownercontactassociation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="owner",
                through="owners.OwnerContactAssociation",
                to="contacts.contact",
                verbose_name="Contacts",
            ),
        ),
    ]
