# Generated by Django 5.0 on 2023-12-13 00:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0006_alter_hut_capacity_alter_hut_capacity_shelter_and_more"),
        ("owners", "0003_alter_owner_contacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerHutProxy",
            fields=[],
            options={
                "verbose_name": "Hut Association",
                "ordering": ("owner__name_i18n",),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("huts.hut",),
        ),
        migrations.AlterModelOptions(
            name="ownercontactassociation",
            options={
                "ordering": ("contact__function__priority", "order", "owner__name"),
                "verbose_name": "Contact Association",
            },
        ),
    ]
