# Generated by Django 5.0 on 2023-12-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owners", "0004_ownerhutproxy_alter_ownercontactassociation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Private comment to the owner, used for review.",
                max_length=500,
                verbose_name="Comment",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Public note to the owner (e.g. 'with the help of ....')",
                max_length=500,
                verbose_name="Note",
            ),
        ),
    ]
