# Generated by Django 5.0 on 2023-12-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owners", "0006_alter_owner_comment_alter_owner_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
