# Generated by Django 5.0 on 2023-12-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owners", "0007_alter_owner_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
