# Generated by Django 5.0 on 2023-12-23 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("owners", "0008_alter_owner_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ownerhutproxy",
            options={"ordering": ("hut_owner__name_i18n",), "verbose_name": "Hut Association"},
        ),
    ]
