# Generated by Django 5.2.9 on 2026-01-04 16:36

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0010_alter_owner_created_alter_owner_modified_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="owner",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_a69e3013",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="48cdbca1a3d57bbf69a779ee298903391db46391",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_a69e3013_9b41f",
                    table="owners_owner",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="ownercontactassociation",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_d201b8fc",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="47ee393fee55a019c96b45ddeac896e59b565ac1",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_d201b8fc_e70ae",
                    table="owners_ownercontactassociation",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="ownerhutproxy",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_f786e619",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="07fbfbcfbe93211a0fba0b9ecd29f1511a0d58bb",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_f786e619_8f8b3",
                    table="huts_hut",
                    when="BEFORE",
                ),
            ),
        ),
    ]
