# Generated by Django 4.2.1 on 2023-05-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(help_text='Ref logo as image', max_length=300, upload_to='huts/orgianizations/logos'),
        ),
    ]
