# Generated by Django 4.2.1 on 2023-05-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='orgianizations/logos/missing.png', help_text='Ref logo as image', max_length=300, upload_to='orgianizations/logos'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True, help_text='Main url', max_length=300),
        ),
    ]
