# Generated by Django 4.2.1 on 2023-05-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_logo_alter_organization_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='orgianizations/logos/missing.png', help_text='Ref logo as image', max_length=300, upload_to='organizations/logos'),
        ),
    ]
