# Generated by Django 4.2.1 on 2023-05-19 08:05

import modeltrans.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'fullname', 'attribution', 'description'), required_languages=(), virtual_fields=True),
        ),
    ]
