# Generated by Django 4.2.1 on 2023-05-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name2_t',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration dictonary'),
        ),
    ]
