# Generated by Django 4.2.1 on 2023-05-28 18:31

from django.db import migrations, models
import server.apps.djjmt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_name2_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name3',
            field=server.apps.djjmt.fields.TranslationJSONField(base_field=models.CharField(max_length=100), blank=True, default='', help_text='Name', langs=[]),
        ),
    ]
