# Generated by Django 4.2.1 on 2023-05-28 18:32

from django.db import migrations, models
import server.apps.djjmt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_name3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name3',
            field=server.apps.djjmt.fields.TranslationJSONField(base_field=models.CharField(default='', max_length=100), blank=True, default=dict, help_text='Name', langs=[]),
        ),
    ]
