# Generated by Django 4.2.1 on 2023-06-01 20:47

from django.db import migrations, models
import server.apps.djjmt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_organization_name3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='i18n',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name2_t',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name3',
        ),
        migrations.AlterField(
            model_name='organization',
            name='attribution',
            field=server.apps.djjmt.fields.TranslationJSONField(base_field=models.CharField(default='', max_length=400), blank=True, default=dict, help_text='Attribution text', langs=[]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=server.apps.djjmt.fields.TranslationJSONField(base_field=models.TextField(default=''), blank=True, default=dict, help_text='Fullname', langs=[]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='fullname',
            field=server.apps.djjmt.fields.TranslationJSONField(base_field=models.CharField(default='', max_length=100), blank=True, default=dict, help_text='Fullname', langs=[]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=server.apps.djjmt.fields.TranslationJSONField(base_field=models.CharField(default='', max_length=100), blank=True, default=dict, help_text='Shortname', langs=[]),
        ),
    ]
