# Generated by Django 4.2.7 on 2023-11-27 12:54

import server.apps.djjmt.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0009_remove_organization_i18n_remove_organization_name2_t_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="attribution",
            field=server.apps.djjmt.fields.TranslationJSONField(
                base_field=models.CharField(default="", max_length=400),
                blank=True,
                default=dict,
                help_text="Attribution text",
                langs=(("de", "German"), ("en", "English"), ("fr", "French"), ("it", "Italian")),
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=server.apps.djjmt.fields.TranslationJSONField(
                base_field=models.TextField(default=""),
                blank=True,
                default=dict,
                help_text="Fullname",
                langs=(("de", "German"), ("en", "English"), ("fr", "French"), ("it", "Italian")),
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="fullname",
            field=server.apps.djjmt.fields.TranslationJSONField(
                base_field=models.CharField(default="", max_length=100),
                blank=True,
                default=dict,
                help_text="Fullname",
                langs=(("de", "German"), ("en", "English"), ("fr", "French"), ("it", "Italian")),
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=server.apps.djjmt.fields.TranslationJSONField(
                base_field=models.CharField(default="", max_length=100),
                blank=True,
                default=dict,
                help_text="Shortname",
                langs=(("de", "German"), ("en", "English"), ("fr", "French"), ("it", "Italian")),
            ),
        ),
    ]
