# Generated by Django 4.2.7 on 2023-12-09 16:41

import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_alter_organization_attribution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("name", "fullname", "description", "attribution", "url"),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="attribution",
            field=models.CharField(default="", help_text="Attribution text", max_length=400),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.TextField(default="", help_text="Fullname"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="fullname",
            field=models.CharField(default="", help_text="Fullname", max_length=100),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(default="", help_text="Shortname", max_length=100),
        ),
    ]
