# Generated by Django 4.2.7 on 2023-12-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0011_organization_i18n_alter_organization_attribution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="attribution",
            field=models.CharField(blank=True, default="", help_text="Attribution text", max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, default="", help_text="Fullname", null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="fullname",
            field=models.CharField(blank=True, default="", help_text="Fullname", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(blank=True, default="", help_text="Shortname", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="url",
            field=models.URLField(blank=True, help_text="Main url", max_length=300, null=True),
        ),
    ]
