# Generated by Django 4.2.7 on 2023-12-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0012_alter_organization_attribution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                default="organizations/logos/missing.png",
                help_text="Ref logo as image",
                max_length=300,
                upload_to="organizations/logos",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, unique=True),
        ),
    ]
