# Generated by Django 5.0 on 2023-12-13 00:45

import colorfield.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0013_alter_organization_logo_alter_organization_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ("order", "name_i18n"), "verbose_name": "Organization"},
        ),
        migrations.AlterField(
            model_name="organization",
            name="attribution",
            field=models.CharField(blank=True, default="", max_length=400, null=True, verbose_name="Attribution"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="color_dark",
            field=colorfield.fields.ColorField(
                default="#61B958",
                help_text="dark theme color as hex number with #",
                image_field=None,
                max_length=18,
                samples=None,
                verbose_name="Dark Color",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="color_light",
            field=colorfield.fields.ColorField(
                default="#4B8E43",
                help_text="light theme color as hex number with #",
                image_field=None,
                max_length=18,
                samples=None,
                verbose_name="Light Color",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="config",
            field=models.JSONField(blank=True, default=dict, verbose_name="Configuration dictonary"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True, default="", help_text="Description", null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="fullname",
            field=models.CharField(blank=True, default="", max_length=100, null=True, verbose_name="Fullname"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="link_hut_pattern",
            field=models.CharField(
                blank=True,
                help_text="Link pattern to corresponding object. Variables to use: {{id}}, {{lang}}, {{props}}, {{config}}.)",
                max_length=300,
                verbose_name="Link patten to object",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                default="organizations/logos/missing.png",
                help_text="Organiztion logo as image",
                max_length=300,
                upload_to="organizations/logos",
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100, null=True, verbose_name="Shortname"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="url",
            field=models.URLField(
                blank=True, help_text="URL to organization's homepage", max_length=300, null=True, verbose_name="URL"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=django.contrib.postgres.indexes.GinIndex(fields=["i18n"], name="organizatio_i18n_965fba_gin"),
        ),
    ]
