# Generated by Django 5.0 on 2023-12-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0014_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_public",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Public"),
        ),
    ]
