# Generated by Django 5.0 on 2023-12-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0016_alter_organization_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
