# Generated by Django 5.2.9 on 2025-12-31 17:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0017_alter_organization_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="color_dark",
            field=colorfield.fields.ColorField(
                default="#61B958",
                help_text="dark theme color as hex number with #",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Dark Color",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="color_light",
            field=colorfield.fields.ColorField(
                default="#4B8E43",
                help_text="light theme color as hex number with #",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Light Color",
            ),
        ),
    ]
