# Generated by Django 5.2.9 on 2026-01-04 16:36

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0019_alter_organization_created_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="organization",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_406b4872",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="67eb51c9239ce309f7ea2f2ce772511eb8ba0440",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_406b4872_f69d7",
                    table="organizations_organization",
                    when="BEFORE",
                ),
            ),
        ),
    ]
