# Generated by Django 5.0.6 on 2024-06-21 15:04

import django.contrib.postgres.indexes
import django.utils.timezone
import model_utils.fields
import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=("name", "fullname", "description", "link"), required_languages=(), virtual_fields=True
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=20, null=True, verbose_name="Shortname")),
                (
                    "fullname",
                    models.CharField(blank=True, default="", max_length=100, null=True, verbose_name="Fullname"),
                ),
                ("description", models.TextField(blank=True, default="", help_text="Description", null=True)),
                ("link", models.URLField(blank=True, max_length=300, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Order")),
                ("attribution_required", models.BooleanField(default=True)),
                ("no_commercial", models.BooleanField(default=True)),
                ("no_modifying", models.BooleanField(default=True)),
                ("share_alike", models.BooleanField(default=True)),
                ("no_publication", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "License",
                "ordering": ("order", "name_i18n"),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(fields=["i18n"], name="licenses_li_i18n_1a04de_gin")
                ],
            },
        ),
    ]
