# Generated by Django 5.0.6 on 2024-06-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="name",
            field=models.CharField(blank=True, default="", max_length=40, null=True, verbose_name="Shortname"),
        ),
    ]
