# Generated by Django 5.1.1 on 2024-10-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0002_alter_license_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="license",
            name="no_publication",
            field=models.BooleanField(default=True),
        ),
    ]
