# Generated by Django 5.1.1 on 2024-10-10 21:21

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0003_alter_license_is_active_alter_license_no_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="slug",
            field=models.SlugField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_\\.]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores, dots or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
