# Generated by Django 5.2.9 on 2026-01-04 16:36

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0005_alter_license_created_alter_license_modified"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="license",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_26a7a6c1",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="fa1d06e99815c6ca743ff565df10c2128381e6bc",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_26a7a6c1_e3fff",
                    table="licenses_license",
                    when="BEFORE",
                ),
            ),
        ),
    ]
