# Generated by Django 5.2.10 on 2026-03-11 13:21

import modeltrans.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0008_rename_link_to_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("name", "fullname", "description", "url"), required_languages=(), virtual_fields=True
            ),
        ),
    ]
