# Generated by Django 6.0.3 on 2026-08-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0015_category_categories__parent__91c7d9_idx"),
        ("licenses", "0009_alter_license_i18n"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="license",
            constraint=models.CheckConstraint(
                condition=models.Q(("review_status__in", ["new", "done", "rejected"])),
                name="licenses_license_review_status_valid",
            ),
        ),
    ]
