name: "setup-uv-env"
description: "Composite action to setup the Python and uv environment."

inputs:
  python-version:
    required: false
    description: "The python version to use"
    default: "3.12"

runs:
  using: "composite"
  steps:
    - name: "Install uv"
      uses: astral-sh/setup-uv@v4
      with:
        # Install a specific version of uv.
        version: "0.5.8"
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --all-extras --dev
      shell: bash
