# Generated by Django 5.2.10 on 2026-01-18 10:44

import django.db.models.deletion
import django.utils.timezone
import modeltrans.fields
import pgtrigger.compiler
import pgtrigger.migrations
import server.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0011_alter_category_symbol_detailed_and_more"),
        ("organizations", "0020_organization_upd_mod_406b4872"),
        ("symbols", "0004_alter_symbol_style"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    server.core.models._AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    server.core.models._AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=("description_day", "description_night"), required_languages=(), virtual_fields=True
                    ),
                ),
                (
                    "code",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="WMO weather code (e.g., 0 = clear sky, 61 = rain)",
                        verbose_name="Weather Code",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, verbose_name="Slug")),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=50,
                        help_text="Priority for WMO code mapping (higher = more important, default: 50)",
                        verbose_name="Priority",
                    ),
                ),
                (
                    "description_day",
                    models.CharField(
                        help_text="Weather description for daytime", max_length=200, verbose_name="Description (Day)"
                    ),
                ),
                (
                    "description_night",
                    models.CharField(
                        help_text="Weather description for nighttime",
                        max_length=200,
                        verbose_name="Description (Night)",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="Weather code ID in the source organization's system",
                        max_length=50,
                        verbose_name="Source ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        help_text="Weather category for grouping",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weather_codes",
                        to="categories.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "source_organization",
                    models.ForeignKey(
                        db_index=False,
                        help_text="Organization providing the weather code mapping",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_codes",
                        to="organizations.organization",
                        verbose_name="Source Organization",
                    ),
                ),
                (
                    "symbol_day",
                    models.ForeignKey(
                        blank=True,
                        help_text="Weather symbol for daytime",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weather_codes_day",
                        to="symbols.symbol",
                        verbose_name="Symbol (Day)",
                    ),
                ),
                (
                    "symbol_night",
                    models.ForeignKey(
                        blank=True,
                        help_text="Weather symbol for nighttime",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weather_codes_night",
                        to="symbols.symbol",
                        verbose_name="Symbol (Night)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weather Code",
                "verbose_name_plural": "Weather Codes",
                "ordering": ("source_organization", "code", "-priority"),
                "indexes": [
                    models.Index(
                        fields=["source_organization", "code", "-priority"], name="meteo_weath_source__c6f7c7_idx"
                    ),
                    models.Index(fields=["source_organization", "slug"], name="meteo_weath_source__153857_idx"),
                    models.Index(fields=["code", "-priority"], name="meteo_weath_code_c969fa_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("source_organization", "slug"), name="unique_source_slug")
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="weathercode",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_3ca7beac",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="d8fd852ac28eacd3ee129521298ee83fb65bfdd2",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_3ca7beac_29b99",
                    table="meteo_weathercode",
                    when="BEFORE",
                ),
            ),
        ),
    ]
