# Generated by Django 5.2.10 on 2026-01-19 12:47

import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
import server.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0011_alter_category_symbol_detailed_and_more"),
        ("meteo", "0002_refactor_weathercode_add_collections"),
        ("symbols", "0004_alter_symbol_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weathercode",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Weather category for grouping",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weather_codes",
                to="categories.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="weathercodesymbol",
            name="created",
            field=server.core.models._AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="weathercodesymbol",
            name="modified",
            field=server.core.models._AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="weathercodesymbolcollection",
            name="created",
            field=server.core.models._AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="weathercodesymbolcollection",
            name="modified",
            field=server.core.models._AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AddIndex(
            model_name="weathercodesymbol",
            index=models.Index(fields=["collection", "weather_code"], name="idx_collection_code"),
        ),
        migrations.AddIndex(
            model_name="weathercodesymbol",
            index=models.Index(fields=["weather_code", "collection"], name="idx_code_collection"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="weathercodesymbol",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_1ecde0ff",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="f1499777b35f7bc18d9df8e9bf2573d2f2855e18",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_1ecde0ff_4fe00",
                    table="meteo_weathercodesymbol",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="weathercodesymbolcollection",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_b743bb65",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="d10e66828614c47592848b373f65abea02997e2a",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_b743bb65_3fce6",
                    table="meteo_weathercodesymbolcollection",
                    when="BEFORE",
                ),
            ),
        ),
    ]
