# Generated by Django 5.2.10 on 2026-01-08 11:22

import django.contrib.postgres.indexes
import django.db.models.deletion
import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=("name", "description"), required_languages=(), virtual_fields=True
                    ),
                ),
                ("slug", models.SlugField(help_text="Unique identifier within parent level")),
                (
                    "name",
                    models.CharField(blank=True, default="", help_text="Category name", max_length=100, null=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Category description", max_length=400, null=True
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, help_text="Display order (lower values appear first)"
                    ),
                ),
                (
                    "symbol",
                    models.ImageField(
                        help_text="Detailed symbol for map display",
                        max_length=300,
                        upload_to="categories/symbols/detailed",
                    ),
                ),
                (
                    "symbol_simple",
                    models.ImageField(
                        help_text="Simple symbol for smaller displays",
                        max_length=300,
                        upload_to="categories/symbols/simple",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        help_text="Icon (typically black/monochrome)", max_length=300, upload_to="categories/icons"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Whether this category is currently active"
                    ),
                ),
                (
                    "default",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default child category (used when parent has children)",
                        limit_choices_to=models.Q(("parent__isnull", False)),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="as_default_for",
                        to="categories.category",
                        verbose_name="Default Child",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category in hierarchy",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="categories.category",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ("parent__order", "order", "slug"),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(fields=["i18n"], name="categories__i18n_bbdb8b_gin"),
                    models.Index(fields=["parent", "order", "slug"], name="categories__parent__d17ddb_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("slug", "parent"), name="unique_slug_per_parent"),
                    models.CheckConstraint(
                        condition=models.Q(("default", models.F("id")), _negated=True), name="default_not_self"
                    ),
                ],
            },
        ),
    ]
