# Generated by Django 5.2.10 on 2026-01-08 11:23

from django.db import migrations


def migrate_huttypes_to_categories(apps, schema_editor):
    """
    Migrate HutType instances to Category model.

    Creates:
    1. Root 'accommodation' category
    2. Child categories for each HutType
    """
    Category = apps.get_model("categories", "Category")
    HutType = apps.get_model("huts", "HutType")

    # Create root accommodation category
    # modeltrans pattern: base field = default lang (de), i18n = {"name_en": "...", "name_fr": "..."}
    accommodation, created = Category.objects.get_or_create(
        slug="accommodation",
        parent=None,
        defaults={
            "name": "Unterkunft",  # Default language (de)
            "description": "Arten von Bergunterkünften",  # Default language (de)
            "i18n": {
                "name_en": "Accommodation",
                "name_fr": "Hébergement",
                "description_en": "Types of mountain accommodations",
                "description_fr": "Types d'hébergements de montagne",
            },
            "order": 10,
            "is_active": True,
        },
    )

    if created:
        print(f"✓ Created root 'accommodation' category")
    else:
        print(f"✓ Root 'accommodation' category already exists")

    # Migrate each HutType - iterate through model instances to properly copy JSONFields
    hut_types = HutType.objects.all().order_by("level", "slug")
    migrated = 0
    skipped = 0

    for ht in hut_types:
        slug = ht.slug

        # Check if category already exists
        if Category.objects.filter(slug=slug, parent=accommodation).exists():
            print(f"  ⊘ Skipping {slug} (already exists)")
            skipped += 1
            continue

        # Copy i18n field directly - this is the correct way to copy JSONFields in migrations
        # modeltrans pattern: base field = default lang, i18n = {"name_en": "...", "name_de": "..."}
        i18n_data = ht.i18n if ht.i18n else {}

        # Create category from hut type
        category = Category.objects.create(
            slug=slug,
            parent=accommodation,
            # Set base fields (default language = de)
            name=ht.name or "",
            description=ht.description or "",
            # Set i18n field (copy from HutType)
            i18n=i18n_data,
            order=ht.level,
            is_active=True,
            # Copy image paths
            symbol=ht.symbol.name if ht.symbol else "",
            symbol_simple=ht.symbol_simple.name if ht.symbol_simple else "",
            icon=ht.icon.name if ht.icon else "",
        )

        print(f"  ✓ Migrated {slug} → Category (id={category.id})")
        migrated += 1

    print(f"\nMigration summary:")
    print(f"  HutTypes found: {len(hut_types)}")
    print(f"  Categories created: {migrated}")
    print(f"  Categories skipped (already exist): {skipped}")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - restore categories back to HutType.

    This copies data from Category back to HutType if it doesn't already exist,
    then deletes the accommodation categories.
    """
    Category = apps.get_model("categories", "Category")
    HutType = apps.get_model("huts", "HutType")

    # Get accommodation root and its children
    accommodation = Category.objects.filter(slug="accommodation", parent=None).first()

    if not accommodation:
        print("✓ No accommodation category found, nothing to reverse")
        return

    # Restore each child category back to HutType
    restored = 0
    skipped = 0

    for category in accommodation.children.all().order_by("order", "slug"):
        # Check if HutType already exists
        if HutType.objects.filter(slug=category.slug).exists():
            print(f"  ⊘ Skipping {category.slug} (HutType already exists)")
            skipped += 1
            continue

        # Get category data using .values() to access all fields
        cat_data = Category.objects.filter(id=category.id).values().first()

        # Build i18n dict from Category (just copy the i18n field)
        i18n_data = cat_data.get('i18n') or {}

        # Restore HutType from category
        hut_type = HutType.objects.create(
            slug=cat_data['slug'],
            # Set base fields (default language)
            name=cat_data.get('name') or "",
            description=cat_data.get('description') or "",
            # Set i18n field (other languages)
            i18n=i18n_data,
            level=cat_data['order'],
            # Copy image paths
            symbol=cat_data['symbol'] or "",
            symbol_simple=cat_data['symbol_simple'] or "",
            icon=cat_data['icon'] or "",
        )

        print(f"  ✓ Restored Category {category.slug} → HutType (id={hut_type.id})")
        restored += 1

    # Now delete the categories
    deleted_count, _ = accommodation.delete()  # Cascade deletes children too

    print(f"\nReverse migration summary:")
    print(f"  HutTypes restored: {restored}")
    print(f"  HutTypes skipped (already exist): {skipped}")
    print(f"  Categories deleted: {deleted_count}")


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("huts", "__latest__"),  # Ensure HutType model is available
    ]

    operations = [
        migrations.RunPython(
            migrate_huttypes_to_categories,
            reverse_migration,
        ),
    ]
