# Generated by Django 5.2.10 on 2026-01-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_rename_symbol_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="symbol_detailed",
            field=models.ImageField(
                blank=True,
                help_text="Detailed symbol for map display",
                max_length=300,
                null=True,
                upload_to="categories/symbols/detailed",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="symbol_mono",
            field=models.ImageField(
                blank=True,
                help_text="Monochrome symbol for UI elements",
                max_length=300,
                null=True,
                upload_to="categories/symbols/mono",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="symbol_simple",
            field=models.ImageField(
                blank=True,
                help_text="Simple symbol for smaller displays",
                max_length=300,
                null=True,
                upload_to="categories/symbols/simple",
            ),
        ),
    ]
