# Generated by Django 5.2.10 on 2026-01-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0004_make_symbol_fields_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                editable=False,
                help_text="Full identifier path (root.slug or parent.slug)",
                max_length=102,
            ),
        ),
    ]
