# Generated by Django 5.2.10 on 2026-01-11 13:06

from django.db import migrations


def populate_identifiers(apps, schema_editor):
    """Populate identifier field for all existing categories."""
    Category = apps.get_model("categories", "Category")

    # Get all categories
    categories = Category.objects.all()

    # Build a map of parent_id -> slug for efficient lookup
    parent_slugs = {cat.id: cat.slug for cat in categories}

    # Update identifiers
    updated_count = 0
    for category in categories:
        if category.parent_id:
            parent_slug = parent_slugs.get(category.parent_id, "root")
            identifier = f"{parent_slug}.{category.slug}"
        else:
            identifier = f"root.{category.slug}"

        category.identifier = identifier
        category.save(update_fields=["identifier"])
        updated_count += 1

    print(f"Updated {updated_count} category identifiers")


def reverse_populate_identifiers(apps, schema_editor):
    """Clear identifier field."""
    Category = apps.get_model("categories", "Category")
    Category.objects.update(identifier="")


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0005_add_identifier_field"),
    ]

    operations = [
        migrations.RunPython(populate_identifiers, reverse_code=reverse_populate_identifiers),
    ]
