# Generated by Django 5.2.10 on 2026-01-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0006_populate_identifier_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="identifier",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Full identifier path (root.slug or parent.slug)",
                max_length=102,
            ),
        ),
    ]
