# Generated by Django 5.2.10 on 2026-01-12 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0007_make_identifier_required"),
        ("symbols", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="symbol_detailed2",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to detailed symbol from Symbols app",
                limit_choices_to={"style": "detailed"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories_detailed",
                to="symbols.symbol",
                verbose_name="Symbol (Detailed) - New",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="symbol_mono2",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to monochrome symbol from Symbols app",
                limit_choices_to={"style": "mono"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories_mono",
                to="symbols.symbol",
                verbose_name="Symbol (Monochrome) - New",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="symbol_simple2",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to simple symbol from Symbols app",
                limit_choices_to={"style": "simple"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories_simple",
                to="symbols.symbol",
                verbose_name="Symbol (Simple) - New",
            ),
        ),
    ]
