# Generated by Django 5.2.10 on 2026-01-13 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0010_cleanup_symbol_fields"),
        ("symbols", "0004_alter_symbol_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="symbol_detailed",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to detailed symbol from Symbols app",
                limit_choices_to={"style": "detailed"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories_detailed",
                to="symbols.symbol",
                verbose_name="Symbol (Detailed)",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="symbol_mono",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to monochrome symbol from Symbols app",
                limit_choices_to={"style": "mono"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories_mono",
                to="symbols.symbol",
                verbose_name="Symbol (Monochrome)",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="symbol_simple",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to simple symbol from Symbols app",
                limit_choices_to={"style": "simple"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories_simple",
                to="symbols.symbol",
                verbose_name="Symbol (Simple)",
            ),
        ),
    ]
