# Generated by Django 5.2.10 on 2026-02-01 20:27

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0011_alter_category_symbol_detailed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color_dark",
            field=colorfield.fields.ColorField(
                default="#61B958",
                help_text="dark theme color as hex number with #",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Dark Color",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="color_light",
            field=colorfield.fields.ColorField(
                default="#4B8E43",
                help_text="light theme color as hex number with #",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Light Color",
            ),
        ),
    ]
