# Generated by Django 5.2.10 on 2026-02-01 21:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0012_category_color_dark_category_color_light"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="color_dark",
        ),
        migrations.RemoveField(
            model_name="category",
            name="color_light",
        ),
        migrations.AddField(
            model_name="category",
            name="color",
            field=colorfield.fields.ColorField(
                default="#4B8E43",
                help_text="theme color as hex number with #",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Color",
            ),
        ),
    ]
