# Generated by Django 5.2.10 on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0013_remove_category_color_dark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="extra",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata as JSON. Example: {'mapcomplete_theme': 'transit', 'custom_field': 'value'}",
                verbose_name="Extra Metadata",
            ),
        ),
    ]
