# Generated by Django 5.2.10 on 2026-03-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0014_category_extra"),
        ("symbols", "0007_fix_style_constraint"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["parent_id"], name="categories__parent__91c7d9_idx"),
        ),
    ]
