# Generated by Django 6.0.3 on 2026-10-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_add_huttype_availability_fr_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_sitemap',
            field=models.CharField(blank=True, choices=[('include', 'include in sitemap'), ('exclude', 'exclude from sitemap')], db_index=True, help_text="Include/exclude this category's places in the sitemap; empty inherits from the parent category (roots default to exclude).", max_length=8, null=True, verbose_name='SEO sitemap policy'),
        ),
    ]
