# Generated by Django 5.0 on 2023-12-12 21:29

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import model_utils.fields
import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactFunction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(fields=("name",), required_languages=(), virtual_fields=True),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="For example 'warden', 'hut owner', 'cook', ...",
                        max_length=100,
                        null=True,
                        verbose_name="Function",
                    ),
                ),
                (
                    "symbol",
                    models.ImageField(
                        default="contacts/function/symbol/default.png",
                        help_text="Contact function symbol, should be square and good visible if small.",
                        max_length=300,
                        upload_to="contacts/function/symbol",
                        verbose_name="Symbol",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Priorty, used for ordering. Lower number has higher priority.",
                        verbose_name="Priority",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Function",
                "ordering": ("priority", "name_i18n"),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(fields=["i18n"], name="contacts_co_i18n_fec081_gin")
                ],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(fields=("note",), required_languages=(), virtual_fields=True),
                ),
                ("name", models.CharField(blank=True, default="", max_length=70, verbose_name="Name")),
                ("email", models.EmailField(blank=True, default="", max_length=70, verbose_name="E-Mail")),
                ("phone", models.CharField(blank=True, default="", max_length=30, verbose_name="Phone")),
                ("mobile", models.CharField(blank=True, default="", max_length=30, verbose_name="Mobile")),
                ("url", models.URLField(blank=True, default="", verbose_name="URL")),
                ("address", models.CharField(blank=True, default="", max_length=200, verbose_name="Address")),
                ("note", models.TextField(blank=True, max_length=500, null=True, verbose_name="Note")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Only shown to admin if not active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Only shown to editors if not public",
                        verbose_name="Public",
                    ),
                ),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="contacts",
                        to="contacts.contactfunction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "ordering": (django.db.models.functions.text.Lower("name"),),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(fields=["i18n"], name="contacts_co_i18n_5d4eca_gin")
                ],
            },
        ),
    ]
