# Generated by Django 5.2.9 on 2026-01-04 16:36

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_created_alter_contact_modified_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="contact",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_bb5ba3d8",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="6954f55caf45395a16e8e94650c22aaee49ee3ae",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_bb5ba3d8_4d74c",
                    table="contacts_contact",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="contactfunction",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_f91f0e61",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="2fa14625c6e670632af729efecd0705b6e680df0",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_f91f0e61_eee92",
                    table="contacts_contactfunction",
                    when="BEFORE",
                ),
            ),
        ),
    ]
