# Generated by Django 5.0.4 on 2024-05-30 15:25

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("email", models.CharField(help_text="E-Mail", max_length=100)),
                (
                    "feedback",
                    models.TextField(blank=True, default="", help_text="Feedback", max_length=10000, null=True),
                ),
                ("url1", models.URLField(blank=True, default="", help_text="URL1", null=True)),
                ("url2", models.URLField(blank=True, default="", help_text="URL2", null=True)),
                ("url3", models.URLField(blank=True, default="", help_text="URL3", null=True)),
                ("url4", models.URLField(blank=True, default="", help_text="URL4", null=True)),
            ],
            options={
                "verbose_name": "Feedback",
            },
        ),
    ]
