# Generated by Django 5.0.4 on 2024-05-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="url1",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="url2",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="url3",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="url4",
        ),
        migrations.AddField(
            model_name="feedback",
            name="urls",
            field=models.JSONField(
                blank=True, default=list, help_text="Additional urls ['url1','url2',...].", verbose_name="URLs"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="email",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="feedback",
            field=models.TextField(blank=True, default="", max_length=10000, null=True),
        ),
    ]
