# Generated by Django 5.0.4 on 2024-05-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0002_remove_feedback_url1_remove_feedback_url2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="feedback_comment",
            field=models.TextField(blank=True, default="", max_length=100000, verbose_name="Review comment"),
        ),
        migrations.AddField(
            model_name="feedback",
            name="feedback_status",
            field=models.CharField(
                choices=[("new", "new"), ("done", "done"), ("work", "work"), ("reject", "reject")],
                default="new",
                max_length=12,
                verbose_name="Review status",
            ),
        ),
    ]
