# Generated by Django 5.0.4 on 2024-05-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0003_feedback_feedback_comment_feedback_feedback_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="subject",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name="feedback",
            constraint=models.CheckConstraint(
                condition=models.Q(("feedback_status__in", ["new", "done", "work", "reject"])),
                name="feedbacks_feedback_feedback_status_valid",
            ),
        ),
    ]
