# Generated by Django 5.0.4 on 2024-05-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0004_feedback_subject_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="feedback",
            new_name="message",
        ),
    ]
