# Generated by Django 5.0.6 on 2024-06-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0005_rename_feedback_feedback_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="get_updates",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="feedback_comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Non public comment to the feedback.",
                max_length=100000,
                verbose_name="Feedback comment",
            ),
        ),
    ]
