# Generated by Django 5.2.9 on 2026-01-04 16:36

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0007_alter_feedback_created_alter_feedback_modified"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="feedback",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_e1449477",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="a7a9a32c01591536846d6889db627e62c64d4fb1",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_e1449477_5cdd1",
                    table="feedbacks_feedback",
                    when="BEFORE",
                ),
            ),
        ),
    ]
