# Generated by Django 5.2.10 on 2026-01-10 14:48

import computedfields.resolver
import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import django_countries.fields
import modeltrans.fields
import pgtrigger.compiler
import pgtrigger.migrations
import server.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0003_rename_symbol_fields"),
        ("images", "0024_image_upd_mod_8c4acfcb_imagetag_upd_mod_43df27cd"),
        ("organizations", "0020_organization_upd_mod_406b4872"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoPlace",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    server.core.models._AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    server.core.models._AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(fields=("name",), required_languages=(), virtual_fields=True),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("elevation", models.IntegerField(blank=True, null=True)),
                ("country_code", django_countries.fields.CountryField(db_index=True, max_length=2)),
                (
                    "importance",
                    models.SmallIntegerField(
                        db_index=True,
                        default=25,
                        help_text="Higher values = more important (0-100 scale)",
                        verbose_name="Importance",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_public", models.BooleanField(db_index=True, default=False)),
                (
                    "is_modified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Any modification compared to the original source were done",
                        verbose_name="Modifed",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="children",
                        to="geometries.geoplace",
                    ),
                ),
                (
                    "place_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, related_name="places", to="categories.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Geo Place",
                "verbose_name_plural": "Geo Places",
                "ordering": ("-importance", django.db.models.functions.text.Lower("name_i18n")),
            },
        ),
        migrations.CreateModel(
            name="GeoPlaceImageAssociation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    server.core.models._AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    server.core.models._AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "geo_place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_associations",
                        to="geometries.geoplace",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="geoplace_details", to="images.image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Image and Geo Place Association",
                "ordering": ("geo_place__name", "order"),
            },
        ),
        migrations.AddField(
            model_name="geoplace",
            name="image_set",
            field=models.ManyToManyField(
                related_name="geo_places",
                through="geometries.GeoPlaceImageAssociation",
                to="images.image",
                verbose_name="Images",
            ),
        ),
        migrations.CreateModel(
            name="GeoPlaceSourceAssociation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    server.core.models._AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    server.core.models._AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("source_props", models.JSONField(blank=True, default=dict, help_text="Source properties.")),
                (
                    "source_id",
                    models.CharField(blank=True, default="", help_text="Source id", max_length=40, null=True),
                ),
                ("import_date", models.DateTimeField(auto_now_add=True)),
                ("confidence", models.FloatField(default=1.0, help_text="Confidence in this source match (0-1)")),
                (
                    "geo_place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_associations",
                        to="geometries.geoplace",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geoplace_sources",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geo Place and Organization Association",
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.AddField(
            model_name="geoplace",
            name="source_set",
            field=models.ManyToManyField(
                related_name="geo_places",
                through="geometries.GeoPlaceSourceAssociation",
                to="organizations.organization",
                verbose_name="Sources",
            ),
        ),
        migrations.AddConstraint(
            model_name="geoplaceimageassociation",
            constraint=models.UniqueConstraint(
                fields=("image", "geo_place"), name="geometries_geoplaceimageassociation_unique_relationships"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="geoplaceimageassociation",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_9692c873",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="7e4e9fa2d5fd6b1996b4043117d21e9961b0e759",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_9692c873_d6dcb",
                    table="geometries_geoplaceimageassociation",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="geoplacesourceassociation",
            constraint=models.UniqueConstraint(
                fields=("organization", "geo_place"), name="geometries_geoplacesourceassociation_unique_relationships"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="geoplacesourceassociation",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_763a4247",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="54be6930ede4b15b1c7e6e1de9a215fe29130bc4",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_763a4247_98e31",
                    table="geometries_geoplacesourceassociation",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="geoplace",
            index=models.Index(fields=["is_active", "is_public"], name="geoplaces_active_public_idx"),
        ),
        migrations.AddIndex(
            model_name="geoplace",
            index=models.Index(fields=["-importance"], name="geometries__importa_d57648_idx"),
        ),
        migrations.AddIndex(
            model_name="geoplace",
            index=django.contrib.postgres.indexes.GinIndex(fields=["i18n"], name="geometries__i18n_cfe888_gin"),
        ),
        migrations.AddIndex(
            model_name="geoplace",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="geoplaces_name_gin_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="geoplace",
            index=django.contrib.postgres.indexes.GistIndex(fields=["location"], name="geoplaces_location_gist_idx"),
        ),
        migrations.AddConstraint(
            model_name="geoplace",
            constraint=models.CheckConstraint(
                condition=models.Q(("country_code__in", ["DE", "CH", "AT", "FR", "IT"])),
                name="geometries_geoplace_country_valid",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="geoplace",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_9351272d",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="2a7feeed8fcf01d53aaff416d05f8462d012119a",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_9351272d_03a21",
                    table="geometries_geoplace",
                    when="BEFORE",
                ),
            ),
        ),
    ]
