# Generated by Django 5.2.10 on 2026-01-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geometries", "0002_create_geoplace_categories"),
    ]

    operations = [
        # Remove old constraint
        migrations.RemoveConstraint(
            model_name="geoplace",
            name="geometries_geoplace_country_valid",
        ),
        # Add new constraint with all Alpine countries
        migrations.AddConstraint(
            model_name="geoplace",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("country_code__in", ["AT", "CH", "DE", "FR", "IT", "LI", "MC", "SI"])
                ),
                name="geometries_geoplace_country_valid",
            ),
        ),
    ]
