# Generated by Django 5.2.10 on 2026-01-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0011_alter_category_symbol_detailed_and_more"),
        ("geometries", "0006_add_geoplace_i18n_tsvector_indexes"),
        ("images", "0024_image_upd_mod_8c4acfcb_imagetag_upd_mod_43df27cd"),
        ("organizations", "0020_organization_upd_mod_406b4872"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="geoplace",
            name="geometries_geoplace_country_valid",
        ),
        migrations.AddConstraint(
            model_name="geoplace",
            constraint=models.CheckConstraint(
                condition=models.Q(("country_code__in", ["DE", "CH", "AT", "FR", "IT"])),
                name="geometries_geoplace_country_valid",
            ),
        ),
    ]
