# Generated by Django 5.2.10 on 2026-01-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geometries", "0007_update_country_constraint_all_countries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geoplace",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
    ]
