# Generated by Django 5.2.10 on 2026-01-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0011_alter_category_symbol_detailed_and_more"),
        ("geometries", "0008_alter_geoplace_name"),
        ("images", "0024_image_upd_mod_8c4acfcb_imagetag_upd_mod_43df27cd"),
        ("organizations", "0020_organization_upd_mod_406b4872"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE tablename = 'geometries_geoplace'
                        AND indexname = 'geoplaces_act_pub_imp_idx'
                    ) THEN
                        CREATE INDEX "geoplaces_act_pub_imp_idx"
                        ON "geometries_geoplace" ("is_active", "is_public", "importance");
                    END IF;
                END $$;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE tablename = 'geometries_geoplace'
                        AND indexname = 'geoplaces_act_pub_cnt_idx'
                    ) THEN
                        CREATE INDEX "geoplaces_act_pub_cnt_idx"
                        ON "geometries_geoplace" ("is_active", "is_public", "country_code");
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS "geoplaces_act_pub_imp_idx";
                DROP INDEX IF EXISTS "geoplaces_act_pub_cnt_idx";
            """,
        ),
    ]
