# Generated by Django 5.2.10 on 2026-01-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0011_alter_category_symbol_detailed_and_more"),
        ("geometries", "0007_update_country_constraint_all_countries"),
        ("images", "0024_image_upd_mod_8c4acfcb_imagetag_upd_mod_43df27cd"),
        ("organizations", "0020_organization_upd_mod_406b4872"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="geoplace",
            index=models.Index(fields=["is_active", "is_public", "importance"], name="geoplaces_act_pub_imp_idx"),
        ),
        migrations.AddIndex(
            model_name="geoplace",
            index=models.Index(fields=["is_active", "is_public", "country_code"], name="geoplaces_act_pub_cnt_idx"),
        ),
    ]
