# Generated by Django 5.2.10 on 2026-01-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geometries", "0008_alter_geoplace_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geoplacesourceassociation",
            name="source_id",
            field=models.CharField(
                blank=True, db_index=True, default="", help_text="Source id", max_length=100, null=True
            ),
        ),
    ]
