# Generated by Django 5.2.10 on 2026-01-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geometries", "0009_geoplace_geoplaces_act_pub_imp_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_indexes
                        WHERE tablename = 'geometries_geoplacesourceassociation'
                        AND indexname = 'geometries_geoplacesourceassociation_source_id_dde97df7'
                    ) THEN
                        CREATE INDEX "geometries_geoplacesourceassociation_source_id_dde97df7"
                        ON "geometries_geoplacesourceassociation" ("source_id");
                        CREATE INDEX "geometries_geoplacesourceassociation_source_id_dde97df7_like"
                        ON "geometries_geoplacesourceassociation" ("source_id" varchar_pattern_ops);
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS "geometries_geoplacesourceassociation_source_id_dde97df7_like";
                DROP INDEX IF EXISTS "geometries_geoplacesourceassociation_source_id_dde97df7";
            """,
        ),
    ]
