# Generated by Django 5.2.10 on 2026-01-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geometries", "0008_geoplace_geoplaces_act_pub_imp_idx_and_more"),
        ("geometries", "0009_alter_geoplacesourceassociation_source_id"),
    ]

    operations = []
