# Generated by Django 5.2.10 on 2026-01-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0011_alter_category_symbol_detailed_and_more"),
        ("geometries", "0010_alter_geoplacesourceassociation_source_id"),
        ("images", "0024_image_upd_mod_8c4acfcb_imagetag_upd_mod_43df27cd"),
        ("organizations", "0020_organization_upd_mod_406b4872"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geoplacesourceassociation",
            name="source_id",
            field=models.CharField(
                blank=True, default="", help_text="Source id", max_length=100, null=True
            ),
        ),
    ]
