# Generated by Django 5.2.10 on 2026-01-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Update Django's state to reflect existing indexes.

    This migration updates the field definition to include db_index=True
    and records the indexes from migration 0009, but doesn't create them
    (they already exist).
    """

    dependencies = [
        ("geometries", "0010_alter_geoplacesourceassociation_source_id"),
    ]

    operations = [
        # Use RunSQL with state_operations to record state without executing
        migrations.RunSQL(
            sql="""
                -- No-op: Index already created in migration 0010
                SELECT 1;
            """,
            reverse_sql="""
                -- No-op: Keep the index
                SELECT 1;
            """,
            state_operations=[
                migrations.AlterField(
                    model_name="geoplacesourceassociation",
                    name="source_id",
                    field=models.CharField(
                        blank=True, db_index=True, default="", help_text="Source id", max_length=100, null=True
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="""
                -- No-op: Indexes already created in migration 0009
                SELECT 1;
            """,
            reverse_sql="""
                -- No-op: Keep the indexes
                SELECT 1;
            """,
            state_operations=[
                migrations.AddIndex(
                    model_name="geoplace",
                    index=models.Index(fields=["is_active", "is_public", "importance"], name="geoplaces_act_pub_imp_idx"),
                ),
                migrations.AddIndex(
                    model_name="geoplace",
                    index=models.Index(fields=["is_active", "is_public", "country_code"], name="geoplaces_act_pub_cnt_idx"),
                ),
            ],
        ),
    ]
