# Generated by Django 5.2.10 on 2026-01-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Sync Django's state with actual database state.

    This migration records that indexes exist without creating them.
    All indexes were created in previous migrations (0009 and 0010).
    """

    dependencies = [
        ("geometries", "0011_alter_geoplacesourceassociation_source_id_and_more"),
    ]

    operations = [
        # These operations record state changes but don't execute
        migrations.AlterField(
            model_name="geoplacesourceassociation",
            name="source_id",
            field=models.CharField(
                blank=True, db_index=True, default="", help_text="Source id", max_length=100, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="geoplace",
            index=models.Index(fields=["is_active", "is_public", "importance"], name="geoplaces_act_pub_imp_idx"),
        ),
        migrations.AddIndex(
            model_name="geoplace",
            index=models.Index(fields=["is_active", "is_public", "country_code"], name="geoplaces_act_pub_cnt_idx"),
        ),
    ]

    def database_forwards(self, apps, schema_editor):
        # Override to prevent execution - indexes already exist
        pass

    def database_backwards(self, apps, schema_editor):
        # Override to prevent dropping - indexes should remain
        pass
