# Generated by Django 5.2.10 on 2026-03-06 19:56

import django.db.models.deletion
import django.utils.timezone
import modeltrans.fields
import pgtrigger.compiler
import pgtrigger.migrations
import server.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0013_remove_category_color_dark_and_more"),
        ("geometries", "0012_populate_geoplace_slugs"),
        ("images", "0024_image_upd_mod_8c4acfcb_imagetag_upd_mod_43df27cd"),
        ("organizations", "0020_organization_upd_mod_406b4872"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmenityDetail",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    server.core.models._AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    server.core.models._AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "operating_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("temporarily_closed", "Temporarily Closed"),
                            ("permanently_closed", "Permanently Closed"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        help_text="Current operating status",
                        max_length=25,
                        verbose_name="Operating Status",
                    ),
                ),
                (
                    "opening_months",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Monthly availability per month: {'jan': 'yes', 'feb': 'yes', ..., 'dec': 'no'}",
                        verbose_name="Opening Months",
                    ),
                ),
                (
                    "opening_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured weekly hours per weekday + public holidays. Example: {'mon': [['09:00', '12:00'], ['14:00', '18:00']], 'tue': [['09:00', '12:00'], ['14:00', '18:00']], ..., 'public_holidays': 'closed'}",
                        verbose_name="Opening Hours",
                    ),
                ),
                (
                    "websites",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of URLs with optional labels: [{'url': 'https://...', 'label': 'Official'}]",
                        verbose_name="Websites",
                    ),
                ),
                (
                    "phones",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of phone numbers: [{'number': '+41 123 456 78 90', 'label': 'Main'}]",
                        verbose_name="Phone Numbers",
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Category-specific overflow data (JSON)",
                        verbose_name="Extra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity Detail",
                "verbose_name_plural": "Amenity Details",
            },
        ),
        migrations.AddField(
            model_name="geoplace",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Long-form text description", verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="geoplace",
            name="detail_type",
            field=models.CharField(
                choices=[
                    ("amenity", "Amenity"),
                    ("transport", "Transport"),
                    ("admin", "Admin"),
                    ("natural", "Natural"),
                    ("none", "None"),
                ],
                db_index=True,
                default="none",
                help_text="Which detail model is attached",
                max_length=20,
                verbose_name="Detail Type",
            ),
        ),
        migrations.AddField(
            model_name="geoplace",
            name="protected_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Field names that sources may not overwrite",
                verbose_name="Protected Fields",
            ),
        ),
        migrations.AddField(
            model_name="geoplace",
            name="review_comment",
            field=models.TextField(
                blank=True, default="", help_text="Internal reviewer note", verbose_name="Review Comment"
            ),
        ),
        migrations.AddField(
            model_name="geoplace",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("review", "Under Review"),
                    ("done", "Done"),
                    ("work", "Work in Progress"),
                    ("reject", "Rejected"),
                ],
                db_index=True,
                default="new",
                max_length=20,
                verbose_name="Review Status",
            ),
        ),
        migrations.AddField(
            model_name="geoplacesourceassociation",
            name="delete_policy",
            field=models.CharField(
                choices=[
                    ("deactivate", "Set is_active=False"),
                    ("keep", "Ignore deletion"),
                    ("delete", "Hard delete"),
                    ("auto_keep", "Deactivate until wodore.modified_date, then keep"),
                ],
                default="deactivate",
                help_text="What happens when this source no longer includes the record",
                max_length=20,
                verbose_name="Delete Policy",
            ),
        ),
        migrations.AddField(
            model_name="geoplacesourceassociation",
            name="modified_date",
            field=models.DateTimeField(
                blank=True, db_index=True, help_text="Last time this source updated the record", null=True
            ),
        ),
        migrations.AddField(
            model_name="geoplacesourceassociation",
            name="priority",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=10,
                help_text="Source precedence for field conflicts (lower number wins)",
                verbose_name="Priority",
            ),
        ),
        migrations.AddField(
            model_name="geoplacesourceassociation",
            name="update_policy",
            field=models.CharField(
                choices=[
                    ("always", "Always overwrite all fields"),
                    ("merge", "Skip fields edited by wodore source"),
                    ("protected", "Never overwrite"),
                    ("auto_protect", "Merge until wodore.modified_date, then protected"),
                ],
                default="always",
                help_text="How this source may update the record",
                max_length=20,
                verbose_name="Update Policy",
            ),
        ),
        migrations.AlterField(
            model_name="geoplace",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("name", "description"), required_languages=(), virtual_fields=True
            ),
        ),
        migrations.AlterField(
            model_name="geoplace",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique URL identifier",
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AddIndex(
            model_name="geoplace",
            index=models.Index(fields=["slug"], name="geometries__slug_8dddc1_idx"),
        ),
        migrations.AddIndex(
            model_name="geoplace",
            index=models.Index(fields=["detail_type"], name="geometries__detail__6f11a2_idx"),
        ),
        migrations.AddIndex(
            model_name="geoplacesourceassociation",
            index=models.Index(fields=["priority"], name="geometries__priorit_02de6d_idx"),
        ),
        migrations.AddConstraint(
            model_name="geoplace",
            constraint=models.CheckConstraint(
                condition=models.Q(("detail_type__in", ["amenity", "transport", "admin", "natural", "none"])),
                name="geometries_geoplace_detail_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="geoplace",
            constraint=models.CheckConstraint(
                condition=models.Q(("review_status__in", ["new", "review", "done", "work", "reject"])),
                name="geometries_geoplace_review_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="geoplacesourceassociation",
            constraint=models.CheckConstraint(
                condition=models.Q(("update_policy__in", ["always", "merge", "protected", "auto_protect"])),
                name="geometries_geoplacesourceassociation_update_policy_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="geoplacesourceassociation",
            constraint=models.CheckConstraint(
                condition=models.Q(("delete_policy__in", ["deactivate", "keep", "delete", "auto_keep"])),
                name="geometries_geoplacesourceassociation_delete_policy_valid",
            ),
        ),
        migrations.AddField(
            model_name="amenitydetail",
            name="geo_place",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="amenity_detail",
                to="geometries.geoplace",
                verbose_name="Geo Place",
            ),
        ),
        migrations.AddIndex(
            model_name="amenitydetail",
            index=models.Index(fields=["operating_status"], name="geometries__operati_7462b6_idx"),
        ),
        migrations.AddConstraint(
            model_name="amenitydetail",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("operating_status__in", ["open", "temporarily_closed", "permanently_closed", "unknown"])
                ),
                name="geometries_amenitydetail_operating_status_valid",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="amenitydetail",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_07c313af",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="2a7f3b1318885b459b51db49ee668b75c892b30a",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_07c313af_df118",
                    table="geometries_amenitydetail",
                    when="BEFORE",
                ),
            ),
        ),
    ]
