# Generated by Django 5.2.10 on 2026-03-06 22:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0013_remove_category_color_dark_and_more"),
        ("geometries", "0013_amenitydetail_geoplace_description_and_more"),
        ("images", "0024_image_upd_mod_8c4acfcb_imagetag_upd_mod_43df27cd"),
        ("organizations", "0020_organization_upd_mod_406b4872"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="geoplace",
            name="geometries_geoplace_review_status_valid",
        ),
        migrations.AddField(
            model_name="geoplace",
            name="shape",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True,
                help_text="Optional polygon geometry for natural features or administrative areas",
                null=True,
                srid=4326,
                verbose_name="Shape",
            ),
        ),
        migrations.AlterField(
            model_name="geoplace",
            name="review_status",
            field=models.CharField(
                choices=[("new", "New"), ("review", "Review Needed"), ("work", "In Review"), ("done", "Reviewed")],
                db_index=True,
                default="new",
                help_text="Editorial state - places shown only when 'new' or 'done'",
                max_length=20,
                verbose_name="Review Status",
            ),
        ),
        migrations.AddConstraint(
            model_name="geoplace",
            constraint=models.CheckConstraint(
                condition=models.Q(("review_status__in", ["new", "review", "work", "done"])),
                name="geometries_geoplace_review_status_valid",
            ),
        ),
    ]
