# Generated by Django 5.2.10 on 2026-03-07 17:17

import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
import server.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geometries", "0014_add_shape_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amenitydetail",
            name="extra",
        ),
        migrations.AddField(
            model_name="geoplace",
            name="extra",
            field=models.JSONField(
                blank=True, default=dict, help_text="Category-specific overflow data (JSON)", verbose_name="Extra"
            ),
        ),
        migrations.AddField(
            model_name="geoplace",
            name="osm_tags",
            field=models.JSONField(
                blank=True, default=dict, help_text="Raw tags from OpenStreetMap (JSON)", verbose_name="OSM Tags"
            ),
        ),
        migrations.AddField(
            model_name="geoplace",
            name="websites",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of URLs with optional labels: [{'url': 'https://...', 'label': 'Official'}]",
                verbose_name="Websites",
            ),
        ),
        migrations.CreateModel(
            name="AdminDetail",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    server.core.models._AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    server.core.models._AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "admin_level",
                    models.SmallIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="OSM administrative level (2=country, 4=state, 6=county, 8=city/municipality, 10=village/hamlet). Can be calculated from parent relationship but stored here for performance and OSM data preservation.",
                        null=True,
                        verbose_name="Admin Level",
                    ),
                ),
                (
                    "population",
                    models.IntegerField(
                        blank=True, help_text="Number of inhabitants", null=True, verbose_name="Population"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="Postal code for this administrative area",
                        max_length=20,
                        null=True,
                        verbose_name="Postal Code",
                    ),
                ),
                (
                    "iso_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-2 code for administrative divisions (e.g., CH-ZH for Zürich)",
                        max_length=10,
                        null=True,
                        verbose_name="ISO Code",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Official website of the administrative entity",
                        null=True,
                        verbose_name="Official Website",
                    ),
                ),
                (
                    "geo_place",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_detail",
                        to="geometries.geoplace",
                        verbose_name="Geo Place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Detail",
                "verbose_name_plural": "Admin Details",
                "indexes": [
                    models.Index(fields=["admin_level"], name="geometries__admin_l_916cab_idx"),
                    models.Index(fields=["population"], name="geometries__populat_c72383_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("admin_level__isnull", True),
                            models.Q(("admin_level__gte", 2), ("admin_level__lte", 10)),
                            _connector="OR",
                        ),
                        name="geometries_admindetail_admin_level_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("population__isnull", True), ("population__gte", 0), _connector="OR"),
                        name="geometries_admindetail_population_positive",
                    ),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="admindetail",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_3ac99f6b",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="9a41906fa2f3250ada61fb362ddff38c7ecf2375",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_3ac99f6b_01ae7",
                    table="geometries_admindetail",
                    when="BEFORE",
                ),
            ),
        ),
    ]
