# Generated by Django 5.2.10 on 2026-03-07 17:21

import server.apps.geometries.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geometries", "0015_remove_amenitydetail_extra_geoplace_extra_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admindetail",
            name="website",
        ),
        migrations.AlterField(
            model_name="geoplace",
            name="websites",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of URLs with optional labels: [{'url': 'https://...', 'label': 'Official'}]",
                validators=[server.apps.geometries.validators.WebsitesValidator()],
                verbose_name="Websites",
            ),
        ),
    ]
