# Generated by Django 5.2.10 on 2026-03-07 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_links", "0001_initial"),
        ("geometries", "0016_remove_admindetail_website_alter_geoplace_websites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geoplace",
            name="websites",
        ),
        migrations.CreateModel(
            name="GeoPlaceExternalLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, help_text="Display order for this link", verbose_name="Order"
                    ),
                ),
                (
                    "external_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_associations",
                        to="external_links.externallink",
                        verbose_name="External Link",
                    ),
                ),
                (
                    "geo_place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_associations",
                        to="geometries.geoplace",
                        verbose_name="Geo Place",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geo Place Link",
                "verbose_name_plural": "Geo Place Links",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="geoplace",
            name="external_links",
            field=models.ManyToManyField(
                help_text="Associated external links (websites, social media, documents, etc.)",
                related_name="geo_places",
                through="geometries.GeoPlaceExternalLink",
                to="external_links.externallink",
                verbose_name="External Links",
            ),
        ),
        migrations.AddIndex(
            model_name="geoplaceexternallink",
            index=models.Index(fields=["geo_place", "order"], name="geometries__geo_pla_17831a_idx"),
        ),
        migrations.AddIndex(
            model_name="geoplaceexternallink",
            index=models.Index(fields=["external_link"], name="geometries__externa_00df5a_idx"),
        ),
        migrations.AddConstraint(
            model_name="geoplaceexternallink",
            constraint=models.UniqueConstraint(
                fields=("geo_place", "external_link"), name="geometries_geoplaceexternallink_unique_place_link"
            ),
        ),
    ]
