# Generated by Django 5.2.10 on 2026-03-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geometries", "0017_remove_geoplace_websites_geoplaceexternallink_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amenitydetail",
            name="websites",
        ),
    ]
