# Generated by Django 5.2.10 on 2026-03-07 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0013_remove_category_color_dark_and_more"),
        ("geometries", "0018_remove_amenitydetail_websites"),
    ]

    operations = [
        migrations.AddField(
            model_name="amenitydetail",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                help_text="Brand category (e.g., Volg, Migros, Coop)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amenity_brands",
                to="categories.category",
                verbose_name="Brand",
            ),
        ),
    ]
