# Generated by Django 5.2.10 on 2026-03-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geometries", "0019_amenitydetail_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geoplace",
            name="is_public",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="geoplacesourceassociation",
            name="delete_policy",
            field=models.CharField(
                choices=[
                    ("deactivate", "Set is_active=False"),
                    ("keep", "Ignore deletion"),
                    ("delete", "Hard delete"),
                    ("auto_keep", "Deactivate until wodore.modified_date, then keep"),
                ],
                default="auto_keep",
                help_text="What happens when this source no longer includes the record",
                max_length=20,
                verbose_name="Delete Policy",
            ),
        ),
        migrations.AlterField(
            model_name="geoplacesourceassociation",
            name="update_policy",
            field=models.CharField(
                choices=[
                    ("always", "Always overwrite all fields"),
                    ("merge", "Skip fields edited by wodore source"),
                    ("protected", "Never overwrite"),
                    ("auto_protect", "Merge until wodore.modified_date, then protected"),
                ],
                default="auto_protect",
                help_text="How this source may update the record",
                max_length=20,
                verbose_name="Update Policy",
            ),
        ),
    ]
