# Generated by Django 5.2.10 on 2026-03-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geometries", "0021_add_osm_import_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="geoplace",
            name="geoplaces_place_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="geoplace",
            name="geoplaces_country_active_type_idx",
        ),
    ]
