# Generated by Django 5.2.10 on 2026-03-11 16:24

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0015_category_categories__parent__91c7d9_idx"),
        ("geometries", "0025_verify_geoplace_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geoplace",
            name="categories",
            field=models.ManyToManyField(
                help_text="Category associations for this place",
                related_name="geo_places",
                through="geometries.GeoPlaceCategory",
                through_fields=("geo_place", "category"),
                to="categories.category",
                verbose_name="Categories",
            ),
        ),
        migrations.AlterField(
            model_name="geoplacecategory",
            name="classifier",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional classifier for this association (e.g., seasonal status)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classifications",
                to="categories.category",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="geoplacecategory",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_52787f17",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="74fe51f491cd58ad50fcbadfb9f0125bc8cf2937",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_52787f17_5b604",
                    table="geometries_geoplace_category",
                    when="BEFORE",
                ),
            ),
        ),
    ]
