# Generated by Django 5.2.10 on 2026-03-13 16:58

from django.db import migrations, models


def recreate_view(apps, schema_editor):
    """Recreate the geoplaces_for_tiles view after slug column alteration."""
    from server.apps.geometries.models.tiles_view import GeoPlacesForTilesView

    # Get SQL from the model's ViewMeta
    sql, params = GeoPlacesForTilesView.ViewMeta.query()

    # Create the view
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP VIEW IF EXISTS geoplaces_for_tiles CASCADE")
        cursor.execute(f"CREATE VIEW geoplaces_for_tiles AS {sql}", params)


class Migration(migrations.Migration):

    dependencies = [
        ("geometries", "0029_add_cleanup_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="geoplace",
            name="geoplaces_is_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="geoplacesourceassociation",
            name="geosa_org_modified_place_idx",
        ),
        migrations.RemoveIndex(
            model_name="geoplacesourceassociation",
            name="geosa_geo_place_idx",
        ),
        # Drop the view before altering slug column (view depends on slug)
        migrations.RunSQL(
            "DROP VIEW IF EXISTS geoplaces_for_tiles CASCADE",
            reverse_sql="DROP VIEW IF EXISTS geoplaces_for_tiles CASCADE",
        ),
        migrations.AlterField(
            model_name="geoplace",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique URL identifier (max 15 chars)",
                max_length=15,
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        # Recreate the view after slug column is altered
        migrations.RunPython(
            code=recreate_view,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
