# Generated by Django 5.2.10 on 2026-03-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geometries", "0030_remove_geoplace_geoplaces_is_active_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geoplace",
            name="name",
            field=models.CharField(blank=True, max_length=200, verbose_name="Name"),
        ),
    ]
