# Generated by Django 6.0.3 on 2026-09-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_add_huttype_availability_fr_it'),
        ('external_links', '0009_add_template_fields'),
        ('geometries', '0042_geoplace_main_language'),
        ('images', '0024_image_upd_mod_8c4acfcb_imagetag_upd_mod_43df27cd'),
        ('organizations', '0020_organization_upd_mod_406b4872'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='geoplace',
            name='geometries_geoplace_review_status_valid',
        ),
        migrations.AddField(
            model_name='geoplace',
            name='description_quality',
            field=models.PositiveSmallIntegerField(blank=True, help_text='LLM quality score (1-10); empty = not assessed yet.', null=True, verbose_name='Description quality'),
        ),
        migrations.AddField(
            model_name='geoplace',
            name='description_quality_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Description quality assessed at'),
        ),
        migrations.AlterField(
            model_name='geoplace',
            name='review_status',
            field=models.CharField(choices=[('new', 'New'), ('review', 'Review Needed'), ('rework', 'needs rework'), ('done', 'Reviewed')], db_index=True, default='new', help_text="Editorial state - places shown only when 'new' or 'done'", max_length=20, verbose_name='Review Status'),
        ),
        migrations.AddConstraint(
            model_name='geoplace',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['new', 'review', 'rework', 'done'])), name='geometries_geoplace_review_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='geoplace',
            constraint=models.CheckConstraint(condition=models.Q(('description_quality__isnull', True), models.Q(('description_quality__gte', 1), ('description_quality__lte', 10)), _connector='OR'), name='geometries_geoplace_description_quality_valid'),
        ),
    ]
