# Generated by Django 6.0.3 on 2026-09-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geometries", "0044_alter_geoplace_description_quality"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geoplaceimageassociation",
            options={
                "ordering": ("geo_place__name", "-score", "id"),
                "verbose_name": "Image and Geo Place Association",
            },
        ),
        # Rename (keeps existing order values).
        migrations.RenameField(
            model_name="geoplaceimageassociation",
            old_name="order",
            new_name="score",
        ),
        migrations.AlterField(
            model_name="geoplaceimageassociation",
            name="score",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Display score — higher is shown first.", null=True
            ),
        ),
    ]
