# Generated by Django 6.0.3 on 2026-09-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geometries", "0045_alter_geoplaceimageassociation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geoplace",
            name="images_pinned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When external images were last pinned from providers (openspec pin-external-images; null = never pinned).",
                null=True,
                verbose_name="Images pinned at",
            ),
        ),
    ]
