# Generated by Django 6.0.3 on 2026-09-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geometries", "0046_geoplace_images_pinned_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geoplace",
            name="images_pinned_at",
            field=models.DateTimeField(
                blank=True, help_text="Last pin sync from providers.", null=True, verbose_name="Images pinned at"
            ),
        ),
    ]
