# Generated by Django 6.0.3 on 2026-10-02 12:50

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the orphaned ObjectVisitDay table from the geometries app.

    #205 introduced ObjectVisitDay in geometries (0048) and moved it to the
    new `visits` app (visits.0001) in the same, unreleased change — the
    geometries table was never used by any shipped code and holds no data
    (confirmed: no v* release contains #205). Deletes the dead duplicate;
    the live model/table lives in `visits`.
    """

    dependencies = [
        ("geometries", "0048_objectvisitday_objectvisitday_upd_mod_e8759613"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="objectvisitday",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="objectvisitday",
            name="geometries__day_0e3f11_idx",
        ),
        migrations.DeleteModel(
            name="ObjectVisitDay",
        ),
    ]
