# Generated by Django 6.0.3 on 2026-09-29 01:04

import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
import server.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectVisitDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    server.core.models._AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    server.core.models._AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                ("day", models.DateField(db_index=True)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "verbose_name": "Object Visit Day",
                "verbose_name_plural": "Object Visit Days",
                "indexes": [models.Index(fields=["day", "-count"], name="visits_obje_day_37577d_idx")],
                "unique_together": {("content_type", "object_id", "day")},
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="objectvisitday",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_46c6b066",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="66c666e08dc1cb7865145129dcc2e95a20a7621c",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_46c6b066_3063b",
                    table="visits_objectvisitday",
                    when="BEFORE",
                ),
            ),
        ),
    ]
