# Generated by Django 5.2.10 on 2026-01-08 00:08

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
import server.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlternativeName",
            fields=[
                (
                    "alternatename_id",
                    models.BigIntegerField(
                        help_text="Unique GeoNames alternate name identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Alternate Name ID",
                    ),
                ),
                (
                    "iso_language",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 639 language code (2-3 chars) optionally followed by country code (e.g., 'zh-CN') or variant (e.g., 'zh-Hant'). Special codes: 'post' for postal codes, 'iata'/'icao'/'faac' for airport codes, 'fr_1793' for French Revolution names, 'abbr' for abbreviations, 'link' for website links, 'wkdt' for Wikidata IDs",
                        max_length=7,
                        verbose_name="ISO Language",
                    ),
                ),
                (
                    "alternate_name",
                    models.CharField(
                        db_index=True,
                        help_text="Alternate name or name variant",
                        max_length=400,
                        verbose_name="Alternate Name",
                    ),
                ),
                (
                    "is_preferred_name",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this is an official/preferred name",
                        verbose_name="Is Preferred Name",
                    ),
                ),
                (
                    "is_short_name",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a short name (e.g., 'California' for 'State of California')",
                        verbose_name="Is Short Name",
                    ),
                ),
                (
                    "is_colloquial",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a colloquial or slang term (e.g., 'Big Apple' for 'New York')",
                        verbose_name="Is Colloquial",
                    ),
                ),
                (
                    "is_historic",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a historic name used in the past (e.g., 'Bombay' for 'Mumbai')",
                        verbose_name="Is Historic",
                    ),
                ),
                (
                    "from_period",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Period when the name started being used",
                        max_length=20,
                        verbose_name="From Period",
                    ),
                ),
                (
                    "to_period",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Period when the name stopped being used",
                        max_length=20,
                        verbose_name="To Period",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alternative Name",
                "verbose_name_plural": "Alternative Names",
                "ordering": ("geoname_id", "iso_language", "alternate_name"),
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Feature identifier: feature_class.feature_code (e.g., T.PK)",
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Feature ID",
                    ),
                ),
                (
                    "feature_class",
                    models.CharField(
                        choices=[
                            ("A", "A · Administrative"),
                            ("H", "H · Hydrographic"),
                            ("L", "L · Area"),
                            ("P", "P · Populated Place"),
                            ("R", "R · Road / Railroad"),
                            ("S", "S · Spot Feature"),
                            ("T", "T · Terrain"),
                            ("U", "U · Undersea"),
                            ("V", "V · Vegetation"),
                        ],
                        db_index=True,
                        help_text="GeoNames feature class (e.g., T, S, P)",
                        max_length=1,
                        verbose_name="Feature Class",
                    ),
                ),
                (
                    "feature_code",
                    models.CharField(
                        help_text="GeoNames feature code (e.g., PK, RSTN)", max_length=10, verbose_name="Feature Code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official name of the feature type", max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description from GeoNames",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Only enabled features are imported into GeoPlace",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "importance",
                    models.SmallIntegerField(
                        default=25,
                        help_text="Base importance for this feature type (0-100 scale, default: 25)",
                        verbose_name="Importance",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Internal notes for manual curation", verbose_name="Notes"
                    ),
                ),
            ],
            options={
                "verbose_name": "GeoNames Feature",
                "verbose_name_plural": "GeoNames Features",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="GeoName",
            fields=[
                (
                    "created",
                    server.core.models._AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    server.core.models._AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "geoname_id",
                    models.BigIntegerField(
                        help_text="Unique GeoNames identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="GeoName ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Primary name from GeoNames", max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "ascii_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ASCII variant of name",
                        max_length=255,
                        verbose_name="ASCII Name",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Geographic coordinates (SRID 4326)", srid=4326, verbose_name="Location"
                    ),
                ),
                (
                    "elevation",
                    models.IntegerField(
                        blank=True, help_text="Elevation in meters", null=True, verbose_name="Elevation"
                    ),
                ),
                (
                    "population",
                    models.BigIntegerField(
                        blank=True, help_text="Population count (if applicable)", null=True, verbose_name="Population"
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        db_index=True, help_text="ISO-3166 country code", max_length=2, verbose_name="Country Code"
                    ),
                ),
                (
                    "admin1_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="First-level administrative division",
                        max_length=20,
                        verbose_name="Admin1 Code",
                    ),
                ),
                (
                    "admin2_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Second-level administrative division",
                        max_length=80,
                        verbose_name="Admin2 Code",
                    ),
                ),
                (
                    "admin3_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Third-level administrative division",
                        max_length=20,
                        verbose_name="Admin3 Code",
                    ),
                ),
                (
                    "admin4_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Fourth-level administrative division",
                        max_length=20,
                        verbose_name="Admin4 Code",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True, default="", help_text="Timezone identifier", max_length=50, verbose_name="Timezone"
                    ),
                ),
                (
                    "modification_date",
                    models.DateField(
                        blank=True, help_text="GeoNames modification date", null=True, verbose_name="Modification Date"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Marked as deleted in GeoNames", verbose_name="Deleted"
                    ),
                ),
            ],
            options={
                "verbose_name": "GeoName",
                "verbose_name_plural": "GeoNames",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Boundary",
            fields=[
                (
                    "created",
                    server.core.models._AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    server.core.models._AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "geoname_id",
                    models.BigIntegerField(
                        help_text="Unique GeoNames identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="GeoName ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Name of area or region", max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "feature_code",
                    models.CharField(
                        db_index=True, help_text="GeoNames feature code", max_length=10, verbose_name="Feature Code"
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        help_text="Polygon boundaries (SRID 4326)", srid=4326, verbose_name="Geometry"
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        db_index=True, help_text="ISO-3166 country code", max_length=2, verbose_name="Country Code"
                    ),
                ),
                (
                    "admin_level",
                    models.SmallIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Administrative level (1-4)",
                        null=True,
                        verbose_name="Admin Level",
                    ),
                ),
                (
                    "modification_date",
                    models.DateField(
                        blank=True,
                        help_text="Last modification date from GeoNames",
                        null=True,
                        verbose_name="Modification Date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boundary",
                "verbose_name_plural": "Boundaries",
                "ordering": ("name",),
                "indexes": [
                    models.Index(fields=["country_code", "admin_level"], name="external_ge_country_deb3a3_idx"),
                    models.Index(fields=["feature_code"], name="external_ge_feature_f9c045_idx"),
                ],
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="boundary",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_1237b89a",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="c84026252b253deb838eb31cdb0ef809c9b7652f",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_1237b89a_bc1d1",
                    table="external_geonames_boundary",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(fields=["feature_class"], name="external_ge_feature_f0f463_idx"),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(fields=["is_enabled"], name="external_ge_is_enab_583d03_idx"),
        ),
        migrations.AddField(
            model_name="geoname",
            name="feature",
            field=models.ForeignKey(
                help_text="GeoNames feature type",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="geonames",
                to="external_geonames.feature",
                verbose_name="Feature",
            ),
        ),
        migrations.AddField(
            model_name="alternativename",
            name="geoname",
            field=models.ForeignKey(
                help_text="GeoNames place this name refers to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternative_names",
                to="external_geonames.geoname",
                verbose_name="GeoName",
            ),
        ),
        migrations.AddIndex(
            model_name="geoname",
            index=models.Index(fields=["feature", "country_code"], name="external_ge_feature_526225_idx"),
        ),
        migrations.AddIndex(
            model_name="geoname",
            index=models.Index(fields=["is_deleted"], name="external_ge_is_dele_b60226_idx"),
        ),
        migrations.AddIndex(
            model_name="geoname",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="geonames_geoname_name_gin_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="geoname",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_88ba7260",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="8bbed18ceac7ba8ac901e085ef062d586c210c4a",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_88ba7260_151ec",
                    table="external_geonames_geoname",
                    when="BEFORE",
                ),
            ),
        ),
        migrations.AddIndex(
            model_name="alternativename",
            index=models.Index(fields=["geoname", "iso_language"], name="external_ge_geoname_27b0ef_idx"),
        ),
        migrations.AddIndex(
            model_name="alternativename",
            index=models.Index(fields=["iso_language", "alternate_name"], name="external_ge_iso_lan_217426_idx"),
        ),
        migrations.AddIndex(
            model_name="alternativename",
            index=models.Index(fields=["is_preferred_name"], name="external_ge_is_pref_4ef179_idx"),
        ),
        migrations.AddIndex(
            model_name="alternativename",
            index=models.Index(fields=["geoname", "is_preferred_name"], name="external_ge_geoname_9dbe22_idx"),
        ),
    ]
