# Generated by Django 5.2.10 on 2026-01-08 00:30

from django.core.management import call_command
from django.db import migrations


def load_features(apps, schema_editor):
    """Load GeoNames feature codes by calling the import_features command."""
    call_command("import_features")


class Migration(migrations.Migration):

    dependencies = [
        ("external_geonames", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_features, reverse_code=migrations.RunPython.noop),
    ]
