# Generated by Django 5.2.10 on 2026-01-08 00:30

import urllib.request
from io import StringIO

from django.db import migrations


def load_features(apps, schema_editor):
    """
    Load GeoNames feature codes directly in the migration.

    Uses the migration's apps registry to avoid issues with fields that
    don't exist yet in the database (like category_id added in 0007).
    """
    Feature = apps.get_model("external_geonames", "Feature")

    url = "https://download.geonames.org/export/dump/featureCodes_en.txt"

    print(f"Fetching feature codes from: {url}")

    try:
        with urllib.request.urlopen(url, timeout=30) as response:
            content = response.read().decode("utf-8")
    except Exception as e:
        print(f"Failed to download feature codes: {e}")
        return

    print("Parsing feature codes...")

    created_count = 0

    for line in StringIO(content):
        line = line.strip()
        if not line or line.startswith("#"):
            continue

        parts = line.split("\t")
        if len(parts) < 2:
            continue

        # Format: "class.code<tab>name<tab>description"
        code_full = parts[0]
        name = parts[1] if len(parts) > 1 else ""
        description = parts[2] if len(parts) > 2 else ""

        # Split class.code
        if "." not in code_full:
            print(f"  Skipping invalid feature code format: {code_full}")
            continue

        feature_class, feature_code = code_full.split(".", 1)
        feature_id = code_full  # Use full "class.code" as ID

        # Only create if it doesn't exist (never overwrite)
        if Feature.objects.filter(id=feature_id).exists():
            continue

        Feature.objects.create(
            id=feature_id,
            feature_class=feature_class,
            feature_code=feature_code,
            name=name,
            description=description,
            is_enabled=False,  # Disabled by default
            importance=25,  # Default low value (0-100 scale)
        )

        created_count += 1

    print(f"Import complete: {created_count} features created")


def reverse_migration(apps, schema_editor):
    """Reverse migration - delete all imported features."""
    Feature = apps.get_model("external_geonames", "Feature")
    count = Feature.objects.all().delete()[0]
    print(f"Deleted {count} features")


class Migration(migrations.Migration):

    dependencies = [
        ("external_geonames", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_features, reverse_migration),
    ]
