# Generated by Django 5.2.10 on 2026-01-08 00:35

from django.db import migrations


def enable_key_features(apps, schema_editor):
    """Enable and set importance for key outdoor/hiking features."""
    Feature = apps.get_model("external_geonames", "Feature")

    # Features to enable with their importance scores (0-100)
    # Higher scores = more important
    # Focus: What would someone search for when planning a hike, ski tour, or outdoor activity?
    feature_config = {
        # === TERRAIN - Very High importance for outdoor activities ===
        "T.PK": 95,      # peak - primary target for hikers
        "T.PKS": 90,     # peaks
        "T.MT": 95,      # mountain
        "T.MTS": 90,     # mountains
        "T.PASS": 80,    # pass - crucial for route planning
        "T.SDL": 65,     # saddle
        "T.VAL": 70,     # valley - major geographic feature
        "T.VALS": 65,    # valleys
        "T.PLAT": 70,    # plateau
        "T.RDG": 65,     # ridge - important for routes
        "T.RDGE": 65,    # ridge(s)
        "T.GRGE": 70,    # gorge - scenic landmark
        "T.CNYN": 70,    # canyon
        "T.HLL": 50,     # hill - lower importance
        "T.HLLS": 45,    # hills
        "T.SPUR": 50,    # spur
        "T.CAPE": 60,    # cape - coastal landmark
        "T.ISL": 70,     # island
        "T.ISLS": 65,    # islands

        # === HYDROGRAPHIC - Important for navigation and scenery ===
        "H.LK": 85,      # lake - major landmark
        "H.LKS": 80,     # lakes
        "H.FLLS": 85,    # waterfall - scenic attraction
        "H.GLCR": 90,    # glacier - important for alpine routes
        "H.STM": 60,     # stream
        "H.STMS": 55,    # streams
        "H.SPNG": 65,    # spring - water source
        "H.RSV": 70,     # reservoir
        "H.BAY": 45,     # bay
        "H.GULF": 45,    # gulf

        # === POPULATED PLACES - For start/end points ===
        "P.PPL": 70,     # populated place - villages/towns
        "P.PPLA": 80,    # seat of first-order admin (major cities)
        "P.PPLA2": 75,   # seat of second-order admin
        "P.PPLA3": 70,   # seat of third-order admin
        "P.PPLA4": 65,   # seat of fourth-order admin
        "P.PPLC": 90,    # capital
        "P.PPLX": 60,    # section of populated place

        # === ADMINISTRATIVE - For regional context ===
        "L.RGN": 75,     # region - important for search/context
        "L.RGNH": 30,    # historical region
        "L.CONT": 20,    # continent

        # === TRANSPORTATION - Essential for trip planning ===
        "S.RSTN": 80,    # railroad station
        "S.RSTP": 70,    # railroad stop
        "S.BUSTN": 75,   # bus station
        "S.BUSTP": 70,   # bus stop
        "S.MTRO": 75,    # metro station
        "S.TRAM": 70,    # tram
        "S.AIRP": 40,    # airport
        "S.FY": 40,      # ferry
        "S.FYT": 50,     # ferry terminal

        # === LANDMARKS - Low-Medium importance ===
        "S.CH": 30,      # church (landmark/waypoint)
        "S.CSTL": 35,    # castle (landmark)
        "S.OBPT": 60,    # observation point - scenic viewpoint
        "S.CAVE": 50,    # cave - attraction
        "S.MNMT": 50,    # monument
        "S.TMPL": 50,    # temple
        "S.RUIN": 45,    # ruin
        "S.ANS": 30,     # archaeological site
        "S.HSTS": 30,    # historical site

        # === FACILITIES - Low importance (not accommodations) ===
        "S.REST": 40,    # restaurant
        "S.MUS": 40,     # museum
        "S.RECG": 45,    # golf course
        "S.PKLT": 35,    # parking lot
        "S.PRK": 60,     # park (nature area)

        # === INFRASTRUCTURE - Low importance ===
        "S.BDG": 30,     # bridge - can be landmark/waypoint
        "S.DAM": 50,     # dam
    }

    # Update features
    for feature_id, importance in feature_config.items():
        Feature.objects.filter(id=feature_id).update(
            is_enabled=True,
            importance=importance
        )

    print(f"Enabled {len(feature_config)} key features for outdoor/hiking use")


class Migration(migrations.Migration):

    dependencies = [
        ("external_geonames", "0002_load_features"),
    ]

    operations = [
        migrations.RunPython(enable_key_features, reverse_code=migrations.RunPython.noop),
    ]
