# Generated by Django 5.2.10 on 2026-01-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_geonames", "0003_enable_key_features"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="feature",
            constraint=models.CheckConstraint(
                condition=models.Q(("feature_class__in", ["A", "H", "L", "P", "R", "S", "T", "U", "V"])),
                name="external_geonames_feature_feature_class_valid",
            ),
        ),
    ]
