# Generated by Django 5.2.10 on 2026-01-08 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_geonames", "0004_add_feature_class_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="geoname",
            name="hierarchy_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Type of hierarchy relationship (e.g., 'ADM' for administrative)",
                max_length=10,
                verbose_name="Hierarchy Type",
            ),
        ),
        migrations.AddField(
            model_name="geoname",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent GeoName in hierarchy",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="external_geonames.geoname",
                verbose_name="Parent",
            ),
        ),
    ]
