# Generated by Django 5.2.10 on 2026-01-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_geonames", "0005_add_hierarchy_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geoname",
            name="hierarchy_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Type of hierarchy relationship (e.g., 'ADM' for administrative)",
                max_length=50,
                verbose_name="Hierarchy Type",
            ),
        ),
    ]
