# Generated by Django 5.2.10 on 2026-01-10 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_rename_symbol_fields"),
        ("external_geonames", "0006_increase_hierarchy_type_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category mapping for import to GeoPlace",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
                verbose_name="Category",
            ),
        ),
    ]
