# Generated by Django 4.2.1 on 2023-05-17 19:44

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('fullname', models.CharField(help_text='Long name of reference', max_length=100)),
                ('url', models.URLField(help_text='Main url', max_length=300)),
                ('link_pattern', models.CharField(help_text='Link to specific entry. Variables to use: {{id}}, {{lang}}, {{props}}, {{config}}.', max_length=300)),
                ('attribution', models.CharField(help_text='Attribution text', max_length=400)),
                ('logo', models.CharField(help_text='Ref logo as image', max_length=40)),
                ('icon', models.CharField(help_text='Ref icon as mdi-<name>', max_length=40)),
                ('color_light', colorfield.fields.ColorField(default='#FFFFFF', help_text='light theme color as hex number with #', image_field=None, max_length=18, samples=None)),
                ('color_dark', colorfield.fields.ColorField(default='#FFFFFF', help_text='dark theme color as hex number with #', image_field=None, max_length=18, samples=None)),
                ('config', models.JSONField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('props_schema', models.JSONField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
            },
        ),
    ]
