# Generated by Django 4.2.7 on 2023-11-27 12:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0010_alter_organization_attribution_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HutSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("source_id", models.CharField(blank=True, help_text="Original id.", max_length=100)),
                # ("point", django.contrib.gis.db.models.fields.PointField(blank=True, default=None, srid=4326)),
                ("source_data", models.JSONField(help_text="Data from the source model.")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("version", models.PositiveSmallIntegerField(default=0)),
                (
                    "review_status",
                    models.CharField(
                        choices=[("new", "new"), ("review", "review"), ("done", "done"), ("reject", "reject")],
                        default="new",
                        max_length=12,
                    ),
                ),
                ("review_comment", models.CharField(default="", max_length=2000)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="organizations.organization"),
                ),
                (
                    "previous_object",
                    models.ForeignKey(
                        blank=True,
                        help_text="Id to the previous object.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="huts.hutsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hut Source",
                "verbose_name_plural": "Hut Sources",
            },
        ),
    ]
