# Generated by Django 4.2.1 on 2023-05-17 21:42

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = []

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fullname', models.CharField(help_text='Long name of reference', max_length=100)),
                ('url', models.URLField(help_text='Main url', max_length=300)),
                ('link_hut_pattern', models.CharField(blank=True, help_text='Link to specific entry. Variables to use: {{id}}, {{lang}}, {{props}}, {{config}}.', max_length=300)),
                ('attribution', models.CharField(blank=True, help_text='Attribution text', max_length=400)),
                ('logo', models.ImageField(help_text='Ref logo as image', max_length=40, upload_to='orgianization/logos')),
                ('color_light', colorfield.fields.ColorField(default='#4B8E43', help_text='light theme color as hex number with #', image_field=None, max_length=18, samples=None)),
                ('color_dark', colorfield.fields.ColorField(default='#61B958', help_text='dark theme color as hex number with #', image_field=None, max_length=18, samples=None)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuration dictonary')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('props_schema', models.JSONField(blank=True, default=dict, help_text='Property schema')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
