# Generated by Django 4.2.1 on 2023-05-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='link_pattern',
            new_name='link_hut_pattern',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='id',
        ),
        migrations.AlterField(
            model_name='organization',
            name='config',
            field=models.JSONField(default={}, help_text='Configuration dictonary'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='props_schema',
            field=models.JSONField(default={}, help_text='Property schema'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
