# Generated by Django 4.2.7 on 2023-11-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hutsource",
            name="previous_object",
            field=models.ForeignKey(
                blank=True,
                help_text="Id to the previous object.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="huts.hutsource",
            ),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="review_comment",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="source_data",
            field=models.JSONField(blank=True, default=dict, help_text="Data from the source model."),
        ),
    ]
