# Generated by Django 5.0 on 2023-12-12 22:05

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("huts", "0001_initial"),
        ("organizations", "0013_alter_organization_logo_alter_organization_order"),
        ("owners", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hut",
            options={"ordering": ("name_i18n",), "verbose_name": "Hut"},
        ),
        migrations.AddIndex(
            model_name="hut",
            index=django.contrib.postgres.indexes.GinIndex(fields=["i18n"], name="huts_hut_i18n_b5f745_gin"),
        ),
        migrations.AddConstraint(
            model_name="hut",
            constraint=models.CheckConstraint(
                check=models.Q(("country__in", ["DE", "CH", "AT", "FR", "IT"])), name="huts_hut_country_valid"
            ),
        ),
    ]
