# Generated by Django 5.0 on 2023-12-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("huts", "0002_alter_hut_options_hut_huts_hut_i18n_b5f745_gin_and_more"),
        ("organizations", "0013_alter_organization_logo_alter_organization_order"),
        ("owners", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hutcontactassociation",
            options={
                "ordering": ("contact__function__priority", "order", "hut__name"),
                "verbose_name": "Contact and Hut Association",
            },
        ),
        migrations.AlterModelOptions(
            name="hutorganizationassociation",
            options={"verbose_name": "Hut and Organization Association"},
        ),
        migrations.AlterUniqueTogether(
            name="hutcontactassociation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="hut",
            constraint=models.CheckConstraint(
                check=models.Q(("review_status__in", ["review", "done", "reject"])), name="huts_hut_review_status_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="hutcontactassociation",
            constraint=models.UniqueConstraint(
                fields=("contact", "hut"), name="huts_hutcontactassociation_unique_relationships"
            ),
        ),
        migrations.AddConstraint(
            model_name="hutorganizationassociation",
            constraint=models.UniqueConstraint(
                fields=("organization", "hut"), name="huts_hutorganizationassociation_unique_relationships"
            ),
        ),
    ]
