# Generated by Django 4.2.7 on 2023-11-27 17:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0002_alter_hutsource_previous_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hutsource",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, srid=4326),
        ),
    ]
