# Generated by Django 4.2.1 on 2023-05-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0002_rename_link_pattern_organization_link_hut_pattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='config',
            field=models.JSONField(default=dict, help_text='Configuration dictonary'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='props_schema',
            field=models.JSONField(default=dict, help_text='Property schema'),
        ),
    ]
