# Generated by Django 5.0 on 2023-12-12 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0003_alter_hutcontactassociation_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hutorganizationassociation",
            unique_together=set(),
        ),
    ]
