# Generated by Django 4.2.7 on 2023-12-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0003_hutsource_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="hutsource",
            name="name",
            field=models.CharField(default="name", help_text="Name of the object object.", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="source_id",
            field=models.CharField(help_text="Original id from source object.", max_length=100),
        ),
    ]
