# Generated by Django 4.2.1 on 2023-05-17 20:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0003_alter_organization_config_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='attribution',
            field=models.CharField(blank=True, help_text='Attribution text', max_length=400),
        ),
        migrations.AlterField(
            model_name='organization',
            name='color_dark',
            field=colorfield.fields.ColorField(default='#61B958', help_text='dark theme color as hex number with #', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='organization',
            name='color_light',
            field=colorfield.fields.ColorField(default='#4B8E43', help_text='light theme color as hex number with #', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='link_hut_pattern',
            field=models.CharField(blank=True, help_text='Link to specific entry. Variables to use: {{id}}, {{lang}}, {{props}}, {{config}}.', max_length=300),
        ),
    ]
