# Generated by Django 5.0 on 2023-12-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0004_alter_hutorganizationassociation_unique_together"),
        ("organizations", "0013_alter_organization_logo_alter_organization_order"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="hutsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("review_status__in", ["new", "review", "done", "old", "reject"])),
                name="huts_hutsource_review_status_valid",
            ),
        ),
    ]
