# Generated by Django 4.2.1 on 2023-05-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0004_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(help_text='Ref logo as image', max_length=40, upload_to='orgianization/logos'),
        ),
    ]
