# Generated by Django 4.2.7 on 2023-12-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0004_hutsource_name_alter_hutsource_source_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hutsource",
            name="review_status",
            field=models.TextField(
                choices=[("new", "new"), ("review", "review"), ("done", "done"), ("old", "old"), ("reject", "reject")],
                default="new",
                max_length=12,
            ),
        ),
    ]
