# Generated by Django 5.0 on 2023-12-13 00:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("huts", "0005_hutsource_huts_hutsource_review_status_valid"),
        ("organizations", "0014_alter_organization_options_and_more"),
        ("owners", "0003_alter_owner_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="capacity",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Capacity"),
        ),
        migrations.AlterField(
            model_name="hut",
            name="capacity_shelter",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Only if an additional shelter is available, e.g. during winter.",
                null=True,
                verbose_name="Shelter Capacity",
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="contacts",
            field=models.ManyToManyField(
                related_name="huts",
                through="huts.HutContactAssociation",
                to="contacts.contact",
                verbose_name="Contacts",
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="description",
            field=models.TextField(max_length=2000, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="hut",
            name="elevation",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name="Elevation"),
        ),
        migrations.AlterField(
            model_name="hut",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="hut",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="hut",
            name="note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Public note, might be some important information",
                max_length=2000,
                verbose_name="Note",
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="organizations",
            field=models.ManyToManyField(
                help_text="This is used to link a hut to different organizations/portals, for example 'SAC', 'Open Stree Map', 'Gipfelbuch', ...",
                through="huts.HutOrganizationAssociation",
                to="organizations.organization",
                verbose_name="Organizations",
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="For example 'SAC Bern' ...",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="huts",
                to="owners.owner",
                verbose_name="Hut owner.",
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="photo",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="Hut photo"),
        ),
        # migrations.AlterField(
        #    model_name="hut",
        #    name="point",
        #    field=django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326, verbose_name="Location"),
        # ),
        migrations.AlterField(
            model_name="hut",
            name="review_comment",
            field=models.CharField(blank=True, default="", max_length=2000, verbose_name="Review comment"),
        ),
        migrations.AlterField(
            model_name="hut",
            name="review_status",
            field=models.TextField(
                choices=[("review", "review"), ("done", "done"), ("reject", "reject")],
                default="review",
                max_length=12,
                verbose_name="Review status",
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="hut",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="huts",
                to="huts.huttype",
                verbose_name="Hut type",
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="url",
            field=models.URLField(blank=True, default="", verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="hut",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sources",
                to="huts.hut",
                verbose_name="Hut",
            ),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="If set to inactive no more updates are done from this source",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="is_current",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Current Entry"),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="name",
            field=models.CharField(help_text="Name of the object", max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, default=None, srid=4326, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="previous_object",
            field=models.ForeignKey(
                blank=True,
                help_text="Id to the previous object.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="huts.hutsource",
                verbose_name="Previous Entry",
            ),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="review_comment",
            field=models.CharField(blank=True, default="", max_length=2000, verbose_name="Review comment"),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="review_status",
            field=models.TextField(
                choices=[("new", "new"), ("review", "review"), ("done", "done"), ("old", "old"), ("reject", "reject")],
                default="new",
                max_length=12,
                verbose_name="Review status",
            ),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="source_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Data from the source model.", verbose_name="Source data as JSON"
            ),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="source_id",
            field=models.CharField(
                help_text="Original ID from source object.", max_length=100, verbose_name="Source ID"
            ),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="version",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Version"),
        ),
    ]
