# Generated by Django 4.2.1 on 2023-05-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0005_alter_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration dictonary'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='props_schema',
            field=models.JSONField(blank=True, default=dict, help_text='Property schema'),
        ),
    ]
