# Generated by Django 4.2.7 on 2023-12-06 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0005_alter_hutsource_review_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hutsource",
            options={
                "ordering": ["name", "organization__order"],
                "verbose_name": "Hut Source",
                "verbose_name_plural": "Hut Sources",
            },
        ),
    ]
