# Generated by Django 5.0 on 2023-12-13 16:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0006_alter_hut_capacity_alter_hut_capacity_shelter_and_more"),
        ("organizations", "0014_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="hutsource",
            name="huts_hutsource_review_status_valid",
        ),
        # migrations.AlterField(
        #    model_name="hut",
        #    name="point",
        #    field=django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326, verbose_name="Location"),
        # ),
        migrations.AlterField(
            model_name="hutsource",
            name="review_status",
            field=models.TextField(
                choices=[
                    ("new", "new"),
                    ("review", "review"),
                    ("done", "done"),
                    ("old", "old"),
                    ("failed", "failed"),
                    ("reject", "reject"),
                ],
                default="new",
                max_length=12,
                verbose_name="Review status",
            ),
        ),
        migrations.AddConstraint(
            model_name="hutsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("review_status__in", ["new", "review", "done", "old", "failed", "reject"])),
                name="huts_hutsource_review_status_valid",
            ),
        ),
    ]
