# Generated by Django 4.2.7 on 2023-12-06 22:00

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0006_alter_hutsource_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hutsource",
            options={
                "ordering": [django.db.models.functions.text.Lower("name"), "organization__order"],
                "verbose_name": "Hut Source",
                "verbose_name_plural": "Hut Sources",
            },
        ),
    ]
