# Generated by Django 5.0 on 2023-12-13 16:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0007_remove_hutsource_huts_hutsource_review_status_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name="Location"),
        ),
    ]
