# Generated by Django 4.2.7 on 2023-12-07 22:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import djjmt.fields
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0010_alter_organization_attribution_and_more"),
        ("huts", "0007_alter_hutsource_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(blank=True, default="", help_text="Name", max_length=70)),
                ("email", models.EmailField(blank=True, default="", help_text="E-Mail", max_length=70)),
                ("phone", models.CharField(blank=True, default="", help_text="Phone", max_length=30)),
                ("mobile", models.CharField(blank=True, default="", help_text="Mobile", max_length=30)),
                ("url", models.URLField(blank=True, default="", help_text="URL")),
                ("address", models.CharField(blank=True, default="", help_text="Address", max_length=200)),
                ("note", models.TextField(blank=True, help_text="Note", max_length=500)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_public", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="ContactFunction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    djjmt.fields.TranslationJSONField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=dict,
                        help_text="Function name",
                        langs=(("de", "German"), ("en", "English"), ("fr", "French"), ("it", "Italian")),
                    ),
                ),
                ("icon", models.CharField(blank=True, help_text="Icon", max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name="Hut",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "name",
                    djjmt.fields.TranslationJSONField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=dict,
                        help_text="Hut name (e.g. SAC Bern)",
                        langs=(("de", "German"), ("en", "English"), ("fr", "French"), ("it", "Italian")),
                    ),
                ),
                (
                    "description",
                    djjmt.fields.TranslationJSONField(
                        base_field=models.TextField(max_length=2000),
                        blank=True,
                        default=dict,
                        help_text="Hut description",
                        langs=(("de", "German"), ("en", "English"), ("fr", "French"), ("it", "Italian")),
                    ),
                ),
                ("url", models.URLField(blank=True, default="", help_text="URL")),
                ("note", models.TextField(blank=True, default="", help_text="note", max_length=2000)),
                ("photo", models.CharField(blank=True, default="", help_text="Photo", max_length=200)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("point", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("elevation", models.DecimalField(decimal_places=1, max_digits=5)),
                ("capacity", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("capacity_shelter", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "review_status",
                    models.TextField(
                        choices=[("review", "review"), ("done", "done"), ("reject", "reject")],
                        default="review",
                        max_length=12,
                    ),
                ),
                ("review_comment", models.CharField(blank=True, default="", max_length=2000)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HutType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                (
                    "name",
                    djjmt.fields.TranslationJSONField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=dict,
                        help_text="Hut type name (e.g. SAC Bern)",
                        langs=(("de", "German"), ("en", "English"), ("fr", "French"), ("it", "Italian")),
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        default="huts_type/icons/normal/unkown.png",
                        help_text="Normal icon",
                        max_length=300,
                        upload_to="huts_type/icons",
                    ),
                ),
                (
                    "icon_simple",
                    models.ImageField(
                        default="huts_type/icons/small/unkown.png",
                        help_text="Simple icon",
                        max_length=300,
                        upload_to="huts_type/icons",
                    ),
                ),
                (
                    "icon_black",
                    models.ImageField(
                        default="huts_type/icons/small/unkown.png",
                        help_text="Black icon",
                        max_length=300,
                        upload_to="huts_type/icons",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    djjmt.fields.TranslationJSONField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=dict,
                        help_text="Owner name (e.g. SAC Bern)",
                        langs=(("de", "German"), ("en", "English"), ("fr", "French"), ("it", "Italian")),
                    ),
                ),
                ("url", models.URLField(blank=True, default="", help_text="URL")),
                ("note", models.TextField(blank=True, default="", help_text="Note", max_length=500)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HutContactAssociation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="huts.contact")),
                ("hut", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="huts.hut")),
            ],
        ),
        migrations.AddField(
            model_name="hut",
            name="contacts",
            field=models.ManyToManyField(related_name="huts", through="huts.HutContactAssociation", to="huts.contact"),
        ),
        migrations.AddField(
            model_name="hut",
            name="organizations",
            field=models.ManyToManyField(
                db_table="hut_organization_association", related_name="huts", to="organizations.organization"
            ),
        ),
        migrations.AddField(
            model_name="hut",
            name="owner",
            field=models.ForeignKey(
                help_text="Hut owner.",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="huts",
                to="huts.owner",
            ),
        ),
        migrations.AddField(
            model_name="hut",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, related_name="huts", to="huts.huttype"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="function",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="huts.contactfunction"),
        ),
    ]
