# Generated by Django 4.2.7 on 2023-12-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0008_contact_contactfunction_hut_huttype_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactfunction",
            name="slug",
            field=models.SlugField(default="slug", unique=True),
            preserve_default=False,
        ),
    ]
