# Generated by Django 5.0 on 2023-12-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("huts", "0008_alter_hut_point"),
        ("organizations", "0014_alter_organization_options_and_more"),
        ("owners", "0004_ownerhutproxy_alter_ownercontactassociation_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="hut",
            name="huts_hut_review_status_valid",
        ),
        migrations.AlterField(
            model_name="hut",
            name="review_status",
            field=models.TextField(
                choices=[("new", "new"), ("review", "review"), ("done", "done"), ("reject", "reject")],
                default="review",
                max_length=12,
                verbose_name="Review status",
            ),
        ),
        migrations.AddConstraint(
            model_name="hut",
            constraint=models.CheckConstraint(
                condition=models.Q(("review_status__in", ["new", "review", "done", "reject"])),
                name="huts_hut_review_status_valid",
            ),
        ),
    ]
