# Generated by Django 5.0 on 2023-12-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0009_remove_hut_huts_hut_review_status_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hut",
            name="is_public",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Public"),
        ),
        migrations.AlterField(
            model_name="hut",
            name="review_comment",
            field=models.TextField(blank=True, default="", max_length=2000, verbose_name="Review comment"),
        ),
        migrations.AlterField(
            model_name="hut",
            name="review_status",
            field=models.CharField(
                choices=[("new", "new"), ("review", "review"), ("done", "done"), ("reject", "reject")],
                default="review",
                max_length=12,
                verbose_name="Review status",
            ),
        ),
    ]
