# Generated by Django 4.2.7 on 2023-12-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0009_contactfunction_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="owner",
            field=models.ForeignKey(
                help_text="Hut owner.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="huts",
                to="huts.owner",
            ),
        ),
    ]
