# Generated by Django 5.0 on 2023-12-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0010_hut_is_public_alter_hut_review_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, help_text="Only shown to admin if not active", verbose_name="Active"
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="is_public",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Only shown to editors if not public", verbose_name="Public"
            ),
        ),
    ]
