# Generated by Django 4.2.7 on 2023-12-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0010_alter_hut_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="elevation",
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
