# Generated by Django 4.2.7 on 2023-12-08 12:37

from server.apps import djjmt

# import djjmt.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0011_alter_hut_elevation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="huttype",
            old_name="icon_simple",
            new_name="symbol_simple",
        ),
        migrations.RemoveField(
            model_name="huttype",
            name="icon_black",
        ),
        migrations.AddField(
            model_name="huttype",
            name="description",
            field=djjmt.fields.TranslationJSONField(
                base_field=models.CharField(max_length=400),
                blank=True,
                default=dict,
                help_text="Hut type description",
                langs=(("de", "German"), ("en", "English"), ("fr", "French"), ("it", "Italian")),
            ),
        ),
        migrations.AddField(
            model_name="huttype",
            name="symbol",
            field=models.ImageField(
                default="huts_type/icons/normal/unkown.png",
                help_text="Normal icon",
                max_length=300,
                upload_to="huts_type/icons",
            ),
        ),
        migrations.AlterField(
            model_name="huttype",
            name="icon",
            field=models.ImageField(
                default="huts_type/icons/small/unkown.png",
                help_text="Black icon",
                max_length=300,
                upload_to="huts_type/icons",
            ),
        ),
        migrations.AlterField(
            model_name="huttype",
            name="name",
            field=djjmt.fields.TranslationJSONField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=dict,
                help_text="Hut type name",
                langs=(("de", "German"), ("en", "English"), ("fr", "French"), ("it", "Italian")),
            ),
        ),
    ]
