# Generated by Django 5.0 on 2023-12-17 20:33

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0011_alter_hut_is_active_alter_hut_is_public"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hut",
            options={"ordering": (django.db.models.functions.text.Lower("name_i18n"),), "verbose_name": "Hut"},
        ),
        migrations.RenameField(
            model_name="hutsource",
            old_name="point",
            new_name="location",
        ),
    ]
