# Generated by Django 4.2.7 on 2023-12-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0012_rename_icon_simple_huttype_symbol_simple_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="huttype",
            name="level",
            field=models.PositiveSmallIntegerField(default=0, help_text="Comfort level, higher is more comfort"),
        ),
    ]
