# Generated by Django 5.0 on 2023-12-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0012_alter_hut_options_rename_point_hutsource_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="hutsource",
            name="source_properties",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional properties from the source model.",
                verbose_name="Source properties as JSON",
            ),
        ),
    ]
