# Generated by Django 4.2.7 on 2023-12-08 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0013_huttype_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="huttype",
            options={"ordering": ["level", "slug"], "verbose_name": "Hut Type", "verbose_name_plural": "Hut Types"},
        ),
        migrations.AddField(
            model_name="hutsource",
            name="hut",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sources", to="huts.hut"
            ),
        ),
    ]
