# Generated by Django 5.0 on 2023-12-20 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0013_hutsource_source_properties"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hut",
            old_name="point",
            new_name="location",
        ),
    ]
