# Generated by Django 4.2.7 on 2023-12-08 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0014_alter_huttype_options_hutsource_hut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="elevation",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="hut",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Hut owner.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="huts",
                to="huts.owner",
            ),
        ),
    ]
