# Generated by Django 5.0 on 2023-12-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0014_rename_point_hut_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hutorganizationassociation",
            name="hut",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="orgs_source", to="huts.hut"
            ),
        ),
    ]
