# Generated by Django 5.0 on 2023-12-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("huts", "0015_alter_hutorganizationassociation_hut"),
        ("organizations", "0015_organization_is_public"),
        ("owners", "0008_alter_owner_slug"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="hut",
            name="huts_hut_review_status_valid",
        ),
        migrations.AlterField(
            model_name="hut",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("review", "review"),
                    ("done", "done"),
                    ("research", "research"),
                    ("reject", "reject"),
                ],
                default="review",
                max_length=12,
                verbose_name="Review status",
            ),
        ),
        migrations.AddConstraint(
            model_name="hut",
            constraint=models.CheckConstraint(
                check=models.Q(("review_status__in", ["new", "review", "done", "research", "reject"])),
                name="huts_hut_review_status_valid",
            ),
        ),
    ]
