# Generated by Django 4.2.7 on 2023-12-08 17:20

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0015_alter_hut_elevation_alter_hut_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="huttype",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("name", "description"), required_languages=(), virtual_fields=True
            ),
        ),
        migrations.AlterField(
            model_name="huttype",
            name="description",
            field=models.CharField(help_text="Hut type description", max_length=400),
        ),
        migrations.AlterField(
            model_name="huttype",
            name="name",
            field=models.CharField(help_text="Hut type name", max_length=100),
        ),
    ]
