# Generated by Django 5.0 on 2023-12-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0016_remove_hut_huts_hut_review_status_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="description",
            field=models.TextField(max_length=10000, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="hut",
            name="review_comment",
            field=models.TextField(blank=True, default="", max_length=10000, verbose_name="Review comment"),
        ),
    ]
