# Generated by Django 4.2.7 on 2023-12-08 18:10

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0016_huttype_i18n_alter_huttype_description_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="huttype",
            index=django.contrib.postgres.indexes.GinIndex(fields=["i18n"], name="huts_huttyp_i18n_4047cb_gin"),
        ),
    ]
