# Generated by Django 5.0 on 2023-12-23 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0017_alter_hut_description_alter_hut_review_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hut",
            old_name="contacts",
            new_name="contact_set",
        ),
        migrations.RenameField(
            model_name="hut",
            old_name="country",
            new_name="country_code",
        ),
        migrations.RenameField(
            model_name="hut",
            old_name="owner",
            new_name="hut_owner",
        ),
        migrations.RenameField(
            model_name="hut",
            old_name="organizations",
            new_name="organization_set",
        ),
        migrations.RenameField(
            model_name="hut",
            old_name="capacity",
            new_name="capacity_open",
        ),
        migrations.RenameField(
            model_name="hut",
            old_name="capacity_shelter",
            new_name="capacity_closed",
        ),
        migrations.RenameField(
            model_name="hut",
            old_name="type",
            new_name="hut_type_open",
        ),
    ]
