# Generated by Django 4.2.7 on 2023-12-08 18:15

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0017_huttype_huts_huttyp_i18n_4047cb_gin"),
    ]

    operations = [
        migrations.AddField(
            model_name="hut",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("name", "description", "note"), required_languages=(), virtual_fields=True
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="description",
            field=models.TextField(help_text="Hut description", max_length=2000),
        ),
        migrations.AlterField(
            model_name="hut",
            name="name",
            field=models.CharField(help_text="Hut name (e.g. SAC Bern)", max_length=100),
        ),
        migrations.AlterField(
            model_name="huttype",
            name="description",
            field=models.CharField(blank=True, default="", help_text="Hut type description", max_length=400),
        ),
        migrations.AlterField(
            model_name="huttype",
            name="name",
            field=models.CharField(blank=True, default="", help_text="Hut type name", max_length=100),
        ),
    ]
