# Generated by Django 4.2.7 on 2023-12-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0018_hut_i18n_alter_hut_description_alter_hut_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="huttype",
            name="icon",
            field=models.ImageField(
                default="huts/types/icons/uknown.png",
                help_text="Black icon",
                max_length=300,
                upload_to="huts_type/icons",
            ),
        ),
        migrations.AlterField(
            model_name="huttype",
            name="symbol",
            field=models.ImageField(
                default="huts/types/symbols/detailed/uknown.png",
                help_text="Normal icon",
                max_length=300,
                upload_to="huts_type/icons",
            ),
        ),
        migrations.AlterField(
            model_name="huttype",
            name="symbol_simple",
            field=models.ImageField(
                default="huts/types/symbols/simple/uknown.png",
                help_text="Simple icon",
                max_length=300,
                upload_to="huts_type/icons",
            ),
        ),
    ]
