# Generated by Django 5.0 on 2023-12-23 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0018_rename_contacts_hut_contact_set_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hut",
            name="hut_type_closed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="hut_closed_set",
                to="huts.huttype",
                verbose_name="Hut type if closed",
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="hut_type_open",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="hut_open_set",
                to="huts.huttype",
                verbose_name="Hut type if open",
            ),
        ),
    ]
