# Generated by Django 5.0 on 2023-12-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("huts", "0019_hut_hut_type_closed_alter_hut_hut_type_open"),
        ("organizations", "0015_organization_is_public"),
        ("owners", "0009_alter_ownerhutproxy_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="hut",
            name="huts_hut_country_valid",
        ),
        migrations.AddConstraint(
            model_name="hut",
            constraint=models.CheckConstraint(
                condition=models.Q(("country_code__in", ["DE", "CH", "AT", "FR", "IT"])), name="huts_hut_country_valid"
            ),
        ),
    ]
