# Generated by Django 5.0 on 2023-12-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0020_remove_hut_huts_hut_country_valid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hut",
            old_name="country_code",
            new_name="country_field",
        ),
        migrations.AlterField(
            model_name="hut",
            name="capacity_closed",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Only if an additional shelter is available, e.g. during winter.",
                null=True,
                verbose_name="Capacity if closed",
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="capacity_open",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Capacity if open"),
        ),
    ]
