# Generated by Django 4.2.7 on 2023-12-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0021_alter_huttype_description_alter_huttype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="huttype",
            name="icon",
            field=models.ImageField(
                default="huts/types/icons/unknown.png",
                help_text="Black icon",
                max_length=300,
                upload_to="huts_type/icons",
            ),
        ),
        migrations.AlterField(
            model_name="huttype",
            name="symbol",
            field=models.ImageField(
                default="huts/types/symbols/detailed/unknown.png",
                help_text="Normal icon",
                max_length=300,
                upload_to="huts_type/icons",
            ),
        ),
        migrations.AlterField(
            model_name="huttype",
            name="symbol_simple",
            field=models.ImageField(
                default="huts/types/symbols/simple/unknown.png",
                help_text="Simple icon",
                max_length=300,
                upload_to="huts_type/icons",
            ),
        ),
    ]
