# Generated by Django 5.0 on 2023-12-24 23:37

import pydantic.main
from django.db import migrations, models

from hut_services import OpenMonthlySchema

default_value = OpenMonthlySchema().model_dump


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0022_remove_hut_huts_hut_country_valid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hut",
            old_name="organization_set",
            new_name="org_set",
        ),
        migrations.AddField(
            model_name="hut",
            name="open_monthly",
            field=models.JSONField(default=default_value, verbose_name="Hut Open"),
        ),
    ]
