# Generated by Django 4.2.7 on 2023-12-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0022_alter_huttype_icon_alter_huttype_symbol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="huttype",
            name="name",
            field=models.CharField(blank=True, default="", help_text="Hut type name", max_length=100, null=True),
        ),
    ]
