# Generated by Django 5.0 on 2023-12-24 23:43

import pydantic.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0023_rename_organization_set_hut_org_set_hut_open_monthly"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="open_monthly",
            field=models.JSONField(default=pydantic.main.BaseModel.model_dump, verbose_name="Hut Open"),
        ),
    ]
