# Generated by Django 4.2.7 on 2023-12-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0023_alter_huttype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="huttype",
            name="description",
            field=models.CharField(blank=True, default="", help_text="Hut type description", max_length=400, null=True),
        ),
    ]
