# Generated by Django 4.2.7 on 2023-12-09 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0013_alter_organization_logo_alter_organization_order"),
        ("huts", "0024_alter_huttype_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hut",
            name="organizations",
        ),
        migrations.CreateModel(
            name="HutOrganizationAssociation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("props", models.JSONField(blank=True, default=dict, help_text="Organization depend properties.")),
                ("hut", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="huts.hut")),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.organization"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hut",
            name="organizations2",
            field=models.ManyToManyField(
                related_name="huts2", through="huts.HutOrganizationAssociation", to="organizations.organization"
            ),
        ),
    ]
