# Generated by Django 4.2.7 on 2023-12-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0013_alter_organization_logo_alter_organization_order"),
        ("huts", "0025_remove_hut_organizations_hutorganizationassociation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hut",
            name="organizations2",
        ),
        migrations.AddField(
            model_name="hut",
            name="organizations",
            field=models.ManyToManyField(
                related_name="huts", through="huts.HutOrganizationAssociation", to="organizations.organization"
            ),
        ),
    ]
