# Generated by Django 5.0 on 2023-12-26 00:44

import pydantic.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0025_alter_hut_open_monthly_alter_hut_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hut",
            old_name="photo",
            new_name="photos",
        ),
        migrations.AlterField(
            model_name="hut",
            name="open_monthly",
            field=models.JSONField(
                default=pydantic.main.BaseModel.model_dump,
                help_text='Possible values: "yes", "maybe", "no" or "unknown". "url" is a link to information when it is open or closed.',
                verbose_name="Hut Open",
            ),
        ),
    ]
