# Generated by Django 5.0 on 2023-12-26 16:28

import pydantic.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0026_rename_photo_hut_photos_alter_hut_open_monthly"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="open_monthly",
            field=models.JSONField(
                default=pydantic.main.BaseModel.model_dump,
                help_text='Possible values: "yes", "maybe", "no" or "unknown". "url" is a link to information when it is open or closed.',
                verbose_name="Hut Open",
            ),
        ),
        migrations.AlterField(
            model_name="huttype",
            name="slug",
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
