# Generated by Django 4.2.7 on 2023-12-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0026_remove_hut_organizations2_hut_organizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="hutorganizationassociation",
            name="source_id",
            field=models.CharField(blank=True, default="", help_text="Source id", max_length=40, null=True),
        ),
    ]
