# Generated by Django 5.0 on 2023-12-26 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0027_alter_hut_open_monthly_alter_huttype_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hutsource",
            name="hut",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sources",
                to="huts.hut",
                verbose_name="Hut",
            ),
        ),
    ]
