# Generated by Django 5.0 on 2023-12-10 16:39

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0027_hutorganizationassociation_source_id"),
        ("organizations", "0013_alter_organization_logo_alter_organization_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hutorganizationassociation",
            options={"verbose_name": "Organizations to Hut"},
        ),
        migrations.AddField(
            model_name="hutorganizationassociation",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AddField(
            model_name="hutorganizationassociation",
            name="link",
            field=models.CharField(
                blank=True, default="", help_text="Link to object by this organisation", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="hutorganizationassociation",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="organizations",
            field=models.ManyToManyField(through="huts.HutOrganizationAssociation", to="organizations.organization"),
        ),
        migrations.AlterField(
            model_name="hutorganizationassociation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="source", to="organizations.organization"
            ),
        ),
        migrations.AlterField(
            model_name="hutorganizationassociation",
            name="props",
            field=models.JSONField(blank=True, default=dict, help_text="Organization dependend properties."),
        ),
        migrations.AlterUniqueTogether(
            name="hutorganizationassociation",
            unique_together={("organization", "hut")},
        ),
    ]
