# Generated by Django 5.0 on 2023-12-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0028_alter_hutsource_hut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hutsource",
            name="review_comment",
            field=models.TextField(blank=True, default="", max_length=10000, verbose_name="Review comment"),
        ),
    ]
