# Generated by Django 5.0 on 2023-12-10 16:41

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0028_alter_hutorganizationassociation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hutcontactassociation",
            options={"verbose_name": "Contacts to Hut"},
        ),
        migrations.AddField(
            model_name="hutcontactassociation",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AddField(
            model_name="hutcontactassociation",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="hutcontactassociation",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="details", to="huts.contact"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hutcontactassociation",
            unique_together={("contact", "hut")},
        ),
    ]
