# Generated by Django 5.0 on 2023-12-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0029_alter_hutcontactassociation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hutorganizationassociation",
            name="link",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Link to object by this organisation",
                max_length=200,
                null=True,
            ),
        ),
    ]
