# Generated by Django 5.0 on 2023-12-27 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0029_alter_hutsource_review_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hutsource",
            name="previous_object",
            field=models.ForeignKey(
                blank=True,
                help_text="Id to the previous object.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="huts.hutsource",
                verbose_name="Previous Entry",
            ),
        ),
    ]
