# Generated by Django 5.0 on 2023-12-11 22:47

import django.db.models.functions.text
import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0030_alter_hutorganizationassociation_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hutsource",
            options={
                "ordering": (django.db.models.functions.text.Lower("name"), "organization__order"),
                "verbose_name": "Hut Source",
                "verbose_name_plural": "Hut Sources",
            },
        ),
        migrations.AlterModelOptions(
            name="huttype",
            options={"ordering": ("level", "slug"), "verbose_name": "Hut Type", "verbose_name_plural": "Hut Types"},
        ),
        migrations.AddField(
            model_name="contact",
            name="i18n",
            field=modeltrans.fields.TranslationField(fields=("note",), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name="contactfunction",
            name="i18n",
            field=modeltrans.fields.TranslationField(fields=("name",), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name="owner",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("name", "note"), required_languages=(), virtual_fields=True
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="note",
            field=models.TextField(blank=True, help_text="Note", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="contactfunction",
            name="name",
            field=models.CharField(blank=True, help_text="Function name", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="owner",
            name="name",
            field=models.CharField(blank=True, help_text="Owner name (e.g. SAC Bern)", max_length=100, null=True),
        ),
    ]
