# Generated by Django 5.0 on 2023-12-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("huts", "0030_alter_hutsource_previous_object"),
        ("organizations", "0017_alter_organization_id"),
        ("owners", "0009_alter_ownerhutproxy_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="hut",
            name="huts_hut_review_status_valid",
        ),
        migrations.AlterField(
            model_name="hut",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("review", "review"),
                    ("done", "done"),
                    ("work", "work"),
                    ("reject", "reject"),
                ],
                default="review",
                max_length=12,
                verbose_name="Review status",
            ),
        ),
        migrations.AddConstraint(
            model_name="hut",
            constraint=models.CheckConstraint(
                condition=models.Q(("review_status__in", ["new", "review", "done", "work", "reject"])),
                name="huts_hut_review_status_valid",
            ),
        ),
    ]
