# Generated by Django 5.0.1 on 2024-01-27 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0031_remove_hut_huts_hut_review_status_valid_and_more"),
        ("organizations", "0017_alter_organization_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="hut",
            name="booking_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hut_booking_set",
                to="organizations.organization",
                verbose_name="Booking Rerefence",
            ),
        ),
        migrations.AddField(
            model_name="hut",
            name="description_attribution",
            field=models.CharField(default="", max_length=100, verbose_name="Descripion Attribution"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hut",
            name="is_modified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Any modification compared to the original source were done",
                verbose_name="Modifed",
            ),
        ),
    ]
