# Generated by Django 5.0 on 2023-12-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0031_alter_hutsource_options_alter_huttype_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactfunction",
            options={"ordering": ("priority", "name_i18n"), "verbose_name": "Function"},
        ),
        migrations.AddField(
            model_name="contactfunction",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Priorty, used for ordering. Higher number has higher priority."
            ),
        ),
    ]
