# Generated by Django 5.0 on 2023-12-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0032_alter_contactfunction_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hutcontactassociation",
            options={
                "ordering": ("contact__function__priority", "order", "hut__name"),
                "verbose_name": "Contacts to Hut",
            },
        ),
        migrations.AddField(
            model_name="owner",
            name="slug",
            field=models.SlugField(default="name", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contactfunction",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Priorty, used for ordering. Lower number has higher priority."
            ),
        ),
    ]
