# Generated by Django 5.0.1 on 2024-01-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0032_hut_booking_ref_hut_description_attribution_and_more"),
        ("organizations", "0017_alter_organization_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="hut",
            name="photos_attribution",
            field=models.CharField(default="", max_length=100, verbose_name="Hut photo attribution"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hut",
            name="description_attribution",
            field=models.CharField(max_length=100, verbose_name="Descripion attribution"),
        ),
        migrations.AlterField(
            model_name="hut",
            name="org_set",
            field=models.ManyToManyField(
                help_text="This is used to link a hut to different organizations/portals, for example 'SAC', 'Open Stree Map', 'Gipfelbuch', ...",
                through="huts.HutOrganizationAssociation",
                to="organizations.organization",
                verbose_name="Sources",
            ),
        ),
    ]
