# Generated by Django 5.0.1 on 2024-01-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0033_hut_photos_attribution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="description_attribution",
            field=models.CharField(max_length=1000, verbose_name="Descripion attribution"),
        ),
        migrations.AlterField(
            model_name="hut",
            name="photos_attribution",
            field=models.CharField(max_length=1000, verbose_name="Hut photo attribution"),
        ),
    ]
