# Generated by Django 5.0 on 2023-12-12 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0034_ownercontactassociation"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="contacts",
            field=models.ManyToManyField(
                related_name="owner", through="huts.OwnerContactAssociation", to="huts.contact"
            ),
        ),
        migrations.AlterField(
            model_name="ownercontactassociation",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="owner_details", to="huts.contact"
            ),
        ),
    ]
