# Generated by Django 5.0.1 on 2024-01-30 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0034_alter_hut_description_attribution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="photos_attribution",
            field=models.CharField(blank=True, default="", max_length=1000, verbose_name="Hut photo attribution"),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="hut",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hut_sources",
                to="huts.hut",
                verbose_name="Hut",
            ),
        ),
    ]
