# Generated by Django 5.0 on 2023-12-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0035_owner_contacts_alter_ownercontactassociation_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="contacts",
            field=models.ManyToManyField(
                null=True, related_name="owner", through="huts.OwnerContactAssociation", to="huts.contact"
            ),
        ),
    ]
