# Generated by Django 5.0.1 on 2024-01-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0035_alter_hut_photos_attribution_alter_hutsource_hut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="description_attribution",
            field=models.CharField(blank=True, default="", max_length=1000, verbose_name="Descripion attribution"),
        ),
    ]
