# Generated by Django 5.0.6 on 2024-09-13 15:27

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0036_alter_hut_description_attribution"),
        ("images", "0014_imagetag_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="HutImageAssociation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("hut", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="huts.hut")),
                ("image", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="images.image")),
            ],
            options={
                "verbose_name": "Image and Hut Association",
                "ordering": ("hut__name", "order"),
            },
        ),
        migrations.AddField(
            model_name="hut",
            name="image_set",
            field=models.ManyToManyField(
                related_name="huts", through="huts.HutImageAssociation", to="images.image", verbose_name="Images"
            ),
        ),
        migrations.AddConstraint(
            model_name="hutimageassociation",
            constraint=models.UniqueConstraint(
                fields=("image", "hut"), name="huts_hutimageassociation_unique_relationships"
            ),
        ),
    ]
