# Generated by Django 5.0 on 2023-12-12 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0036_alter_owner_contacts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="contacts",
        ),
    ]
