# Generated by Django 5.0 on 2023-12-12 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0037_remove_owner_contacts"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OwnerContactAssociation",
        ),
    ]
