# Generated by Django 5.0.6 on 2024-09-30 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0037_hutimageassociation_hut_image_set_and_more"),
        ("images", "0014_imagetag_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hutimageassociation",
            name="hut",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="huts", to="huts.hut"),
        ),
        migrations.AlterField(
            model_name="hutimageassociation",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="details", to="images.image"
            ),
        ),
    ]
