# Generated by Django 5.0 on 2023-12-12 13:48

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("huts", "0038_delete_ownercontactassociation"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerContactAssociation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="owners", to="huts.contact"
                    ),
                ),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="huts.owner")),
            ],
            options={
                "verbose_name": "Contacts to Owner",
                "ordering": ("contact__function__priority", "order", "owner__name"),
                "unique_together": {("contact", "owner")},
            },
        ),
    ]
