# Generated by Django 5.1.1 on 2024-10-10 21:21

import server.apps.huts.models._hut
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0038_alter_hutimageassociation_hut_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="open_monthly",
            field=models.JSONField(
                default=server.apps.huts.models._hut._monthly_open_default_value,
                help_text='Possible values: "yes", "yesish", "maybe", "no", "noish" or "unknown". "url" is a link to information when it is open or closed.',
                verbose_name="Hut Open",
            ),
        ),
    ]
