# Generated by Django 5.2.9 on 2025-12-31 17:48

import server.apps.huts.models._hut
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0039_alter_hut_open_monthly"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="open_monthly",
            field=models.JSONField(
                default=server.apps.huts.models._hut._monthly_open_default_value, verbose_name="Hut Open"
            ),
        ),
        migrations.AlterField(
            model_name="huttype",
            name="symbol",
            field=models.ImageField(
                default="huts/types/symbols/detailed/unknown.png",
                help_text="Normal icon",
                max_length=300,
                upload_to="huts_type/symbols/detailed",
            ),
        ),
        migrations.AlterField(
            model_name="huttype",
            name="symbol_simple",
            field=models.ImageField(
                default="huts/types/symbols/simple/unknown.png",
                help_text="Simple icon",
                max_length=300,
                upload_to="huts_type/symbols/simple",
            ),
        ),
    ]
