# Generated by Django 5.0 on 2023-12-12 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("huts", "0040_owner_contacts_alter_ownercontactassociation_contact"),
        ("owners", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="function",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="contacts",
        ),
        migrations.AlterField(
            model_name="hutcontactassociation",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="details", to="contacts.contact"
            ),
        ),
        # migrations.RemoveField(
        #    model_name="ownercontactassociation",
        #    name="contact",
        # ),
        # migrations.RemoveField(
        #    model_name="ownercontactassociation",
        #    name="owner",
        # ),
        migrations.AlterField(
            model_name="hut",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Hut owner.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="huts",
                to="owners.owner",
            ),
        ),
        # migrations.AlterUniqueTogether(
        #    name="ownercontactassociation",
        #    unique_together=None,
        # ),
        migrations.AlterField(
            model_name="hut",
            name="contacts",
            field=models.ManyToManyField(
                related_name="huts", through="huts.HutContactAssociation", to="contacts.contact"
            ),
        ),
        migrations.DeleteModel(
            name="ContactFunction",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="OwnerContactAssociation",
        ),
        migrations.DeleteModel(
            name="Owner",
        ),
    ]
