# Generated by Django 5.2.9 on 2025-12-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0040_alter_hut_open_monthly_alter_huttype_symbol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hut",
            name="availability_is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Inactive huts have availability checked weekly instead of based on occupancy",
                verbose_name="Availability Tracking Active",
            ),
        ),
    ]
