# Generated by Django 5.2.9 on 2025-12-31 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0041_hut_availability_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hut",
            name="availability_is_active",
        ),
    ]
