# Generated by Django 5.2.9 on 2026-01-04 16:23

import django.utils.timezone
import server.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0042_remove_hut_availability_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="created",
            field=server.core.models._AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="modified",
            field=server.core.models._AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="hutcontactassociation",
            name="created",
            field=server.core.models._AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="hutcontactassociation",
            name="modified",
            field=server.core.models._AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="hutimageassociation",
            name="created",
            field=server.core.models._AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="hutimageassociation",
            name="modified",
            field=server.core.models._AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="hutorganizationassociation",
            name="created",
            field=server.core.models._AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="hutorganizationassociation",
            name="modified",
            field=server.core.models._AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="created",
            field=server.core.models._AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="hutsource",
            name="modified",
            field=server.core.models._AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
    ]
