# Generated by Django 5.2.9 on 2026-01-04 16:36

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0043_alter_hut_created_alter_hut_modified_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="hutcontactassociation",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_16e936d1",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="e121d5ebc78378193118e3147b82973151f18782",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_16e936d1_4ae5e",
                    table="huts_hutcontactassociation",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hutimageassociation",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_fa74aff7",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="02692eeb0ea3ddfb6929223a0e8c3501385bac82",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_fa74aff7_bf385",
                    table="huts_hutimageassociation",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hutorganizationassociation",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_0d7c7445",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="6065922be7f71938ee44f778034f9cb3351e9da5",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_0d7c7445_485c2",
                    table="huts_hutorganizationassociation",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hutsource",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_0952b754",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="77c627b3a0f5b043cdfcbededbfaaf87250fb3e4",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_0952b754_49281",
                    table="huts_hutsource",
                    when="BEFORE",
                ),
            ),
        ),
    ]
