# Generated by Django 5.2.9 on 2026-01-04 16:36

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0044_hutcontactassociation_upd_mod_16e936d1_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="hut",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_1e0a79f8",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="b0a8d8c1f5a804fc8c3f8d7e5e0b17b7809b41d3",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_1e0a79f8_bcb5b",
                    table="huts_hut",
                    when="BEFORE",
                ),
            ),
        ),
    ]
