# Generated by Django 5.2.9 on 2026-01-04 21:53

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0045_hut_trigger"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="hut",
            name="upd_mod_1e0a79f8",
        ),
    ]
