# Generated by Django 5.2.9 on 2026-01-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_contact_upd_mod_bb5ba3d8_and_more"),
        ("huts", "0046_remove_hut_upd_mod_1e0a79f8"),
        ("images", "0024_image_upd_mod_8c4acfcb_imagetag_upd_mod_43df27cd"),
        ("organizations", "0020_organization_upd_mod_406b4872"),
        ("owners", "0011_owner_upd_mod_a69e3013_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="hut",
            index=models.Index(fields=["is_active", "is_public"], name="hut_active_public_idx"),
        ),
        migrations.AddIndex(
            model_name="hut",
            index=models.Index(fields=["location"], name="hut_location_gist_idx"),
        ),
    ]
