# Generated by Django 5.2.9 on 2026-01-06 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0047_add_performance_indexes"),
        ("organizations", "0020_organization_upd_mod_406b4872"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hut",
            old_name="booking_ref",
            new_name="availability_source_ref",
        ),
        migrations.AlterField(
            model_name="hut",
            name="availability_source_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization providing online booking/availability data for this hut",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hut_availability_source_set",
                to="organizations.organization",
                verbose_name="Availability Source Reference",
            ),
        ),
    ]
