# Generated by Django 5.2.9 on 2026-01-06 21:35

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_contact_upd_mod_bb5ba3d8_and_more"),
        ("huts", "0049_add_search_extensions"),
        ("images", "0024_image_upd_mod_8c4acfcb_imagetag_upd_mod_43df27cd"),
        ("organizations", "0020_organization_upd_mod_406b4872"),
        ("owners", "0011_owner_upd_mod_a69e3013_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="hut",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="hut_name_gin_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
