# Generated by Django 5.2.10 on 2026-01-10 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),  # Only need Category model to exist, not the data migration
        ("huts", "0050_add_name_gin_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="hut_type_closed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="huts_closed",
                to="categories.category",
                verbose_name="Hut type if closed",
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="hut_type_open",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="huts_open",
                to="categories.category",
                verbose_name="Hut type if open",
            ),
        ),
        migrations.DeleteModel(
            name="HutType",
        ),
    ]
