# Generated by Django 5.2.10 on 2026-01-10 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_migrate_huttype_data"),  # Need HutTypes copied to Categories first
        ("huts", "0050_add_name_gin_index"),
        # availability.0009 repoints HutAvailability(History).hut_type from
        # huts.HutType (removed below) to categories.Category. It must run
        # first, otherwise the lazy HutType reference cannot be resolved on a
        # fresh database (`Related model 'huts.huttype' cannot be resolved`).
        # Dependency-only change: no effect on already-migrated databases.
        ("availability", "0009_alter_hutavailability_hut_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="hut_type_closed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="huts_closed",
                to="categories.category",
                verbose_name="Hut type if closed",
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="hut_type_open",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="huts_open",
                to="categories.category",
                verbose_name="Hut type if open",
            ),
        ),
        migrations.DeleteModel(
            name="HutType",
        ),
    ]
