# Generated by Django 5.2.10 on 2026-01-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0052_remove_hut_huts_hut_country_valid_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE VIEW huts_for_tiles AS
            SELECT
              h.slug,
              h.location,
              h.elevation,
              h.capacity_open,
              h.capacity_closed,

              -- Multilingual names with fallbacks
              COALESCE(h.i18n->>'name_de', h.i18n->>'name_en', h.i18n->>'name_fr', h.name) as name_de,
              COALESCE(h.i18n->>'name_en', h.i18n->>'name_de', h.i18n->>'name_fr', h.name) as name_en,
              COALESCE(h.i18n->>'name_fr', h.i18n->>'name_de', h.i18n->>'name_en', h.name) as name_fr,
              COALESCE(h.i18n->>'name_it', h.i18n->>'name_de', h.i18n->>'name_en', h.name) as name_it,

              -- Hut type (open state)
              cat_open.slug as type_open_slug,
              cat_open."order" as type_open_order,

              -- Hut type (closed state)
              cat_closed.slug as type_closed_slug,
              cat_closed."order" as type_closed_order,

              -- Availability status
              (h.availability_source_ref_id IS NOT NULL) as has_availability,

              -- Owner information
              owner.slug as owner_slug,
              owner.name as owner_name,

              -- Organization sources (array of objects with slug and source_id)
              COALESCE(
                (
                  SELECT json_agg(
                    json_build_object(
                      'slug', o.slug,
                      'source_id', hoa.source_id
                    )
                  )
                  FROM huts_hutorganizationassociation hoa
                  LEFT JOIN organizations_organization o ON hoa.organization_id = o.id
                  WHERE hoa.hut_id = h.id AND o.slug IS NOT NULL
                ),
                '[]'::json
              ) as sources

            FROM huts_hut h
            LEFT JOIN categories_category cat_open ON h.hut_type_open_id = cat_open.id
            LEFT JOIN categories_category cat_closed ON h.hut_type_closed_id = cat_closed.id
            LEFT JOIN owners_owner owner ON h.hut_owner_id = owner.id
            WHERE h.is_public = true AND h.is_active = true
            """,
            reverse_sql="DROP VIEW IF EXISTS huts_for_tiles",
        ),
    ]
