# Generated by Django 6.0.3 on 2026-09-21 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0015_category_categories__parent__91c7d9_idx"),
        ("huts", "0058_update_tiles_view_single_category_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="hut_type_closed",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("parent__slug", "accommodation")),
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="huts_closed",
                to="categories.category",
                verbose_name="Hut type if closed",
            ),
        ),
        migrations.AlterField(
            model_name="hut",
            name="hut_type_open",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("parent__slug", "accommodation")),
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="huts_open",
                to="categories.category",
                verbose_name="Hut type if open",
            ),
        ),
    ]
