# Generated by Django 6.0.3 on 2026-09-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_add_huttype_availability_fr_it'),
        ('contacts', '0003_contact_upd_mod_bb5ba3d8_and_more'),
        ('huts', '0059_alter_hut_hut_type_closed_alter_hut_hut_type_open'),
        ('images', '0024_image_upd_mod_8c4acfcb_imagetag_upd_mod_43df27cd'),
        ('organizations', '0020_organization_upd_mod_406b4872'),
        ('owners', '0011_owner_upd_mod_a69e3013_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hut',
            name='main_language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('fr', 'French'), ('it', 'Italian')], default='de', help_text='Language of the original texts; other languages are translated from it.', max_length=10, verbose_name='Main language'),
        ),
        migrations.AddConstraint(
            model_name='hut',
            constraint=models.CheckConstraint(condition=models.Q(('main_language__in', ['de', 'en', 'fr', 'it'])), name='huts_hut_main_language_valid'),
        ),
    ]
