# Generated by Django 6.0.3 on 2026-09-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_add_huttype_availability_fr_it'),
        ('contacts', '0003_contact_upd_mod_bb5ba3d8_and_more'),
        ('huts', '0060_hut_main_language'),
        ('images', '0024_image_upd_mod_8c4acfcb_imagetag_upd_mod_43df27cd'),
        ('organizations', '0020_organization_upd_mod_406b4872'),
        ('owners', '0011_owner_upd_mod_a69e3013_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hut',
            name='huts_hut_review_status_valid',
        ),
        migrations.AddField(
            model_name='hut',
            name='description_quality',
            field=models.PositiveSmallIntegerField(blank=True, help_text='LLM quality score (1-10); empty = not assessed yet.', null=True, verbose_name='Description quality'),
        ),
        migrations.AddField(
            model_name='hut',
            name='description_quality_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Description quality assessed at'),
        ),
        migrations.AlterField(
            model_name='hut',
            name='review_status',
            field=models.CharField(choices=[('new', 'new'), ('review', 'review'), ('done', 'done'), ('rework', 'needs rework'), ('reject', 'reject')], default='review', max_length=12, verbose_name='Review status'),
        ),
        migrations.AddConstraint(
            model_name='hut',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['new', 'review', 'done', 'rework', 'reject'])), name='huts_hut_review_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='hut',
            constraint=models.CheckConstraint(condition=models.Q(('description_quality__isnull', True), models.Q(('description_quality__gte', 1), ('description_quality__lte', 10)), _connector='OR'), name='huts_hut_description_quality_valid'),
        ),
    ]
