# Generated by Django 6.0.3 on 2026-09-24 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0061_description_quality_rework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hut',
            name='description_quality',
            field=models.PositiveSmallIntegerField(blank=True, help_text='LLM quality score of the description: 1 = low (thin/marketing text), 10 = excellent. Empty means not assessed yet.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Description quality'),
        ),
    ]
