# Generated by Django 6.0.3 on 2026-09-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0062_alter_hut_description_quality"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hutimageassociation",
            options={"ordering": ("hut__name", "-score", "id"), "verbose_name": "Image and Hut Association"},
        ),
        # Rename (keeps existing order values) — the score semantics are the
        # openspec pin-external-images display score.
        migrations.RenameField(
            model_name="hutimageassociation",
            old_name="order",
            new_name="score",
        ),
        migrations.AlterField(
            model_name="hutimageassociation",
            name="score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Display score — higher is shown first; pinned external images carry their provider score.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hut",
            name="images_pinned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When external images were last pinned from providers (openspec pin-external-images; null = never pinned).",
                null=True,
                verbose_name="Images pinned at",
            ),
        ),
    ]
