# Generated by Django 6.0.3 on 2026-09-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huts", "0063_alter_hutimageassociation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hut",
            name="images_pinned_at",
            field=models.DateTimeField(
                blank=True, help_text="Last pin sync from providers.", null=True, verbose_name="Images pinned at"
            ),
        ),
    ]
