# Generated by Django 5.0.6 on 2024-06-23 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_image_uploader"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="uploader",
        ),
        migrations.RemoveField(
            model_name="image",
            name="uploader_anonym",
        ),
        migrations.AddField(
            model_name="image",
            name="uploaded_by_anonym",
            field=models.CharField(
                blank=True,
                default="",
                help_text="E-mail or name of the anonymous uploader",
                max_length=255,
                null=True,
                verbose_name="Uploaded By (Anonym)",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="uploaded_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Uploaded By (User)",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="granted_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="E-mail or name of the granted persion",
                max_length=255,
                null=True,
                verbose_name="Granted By",
            ),
        ),
    ]
