# Generated by Django 5.0.6 on 2024-06-23 20:35

import django.contrib.postgres.indexes
import django.utils.timezone
import model_utils.fields
import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_remove_image_uploader_remove_image_uploader_anonym_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="tags",
        ),
        migrations.CreateModel(
            name="ImageTag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(fields=("name",), required_languages=(), virtual_fields=True),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("name", models.TextField(max_length=50, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Image Tag",
                "ordering": ("slug",),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(fields=["i18n"], name="images_imag_i18n_4c8053_gin")
                ],
            },
        ),
        migrations.AddField(
            model_name="image",
            name="tags_link",
            field=models.ManyToManyField(related_name="images", to="images.imagetag", verbose_name="Tags"),
        ),
    ]
