# Generated by Django 5.0.6 on 2024-06-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_remove_image_tags_imagetag_image_tags_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="tags_link",
            new_name="tags",
        ),
    ]
