# Generated by Django 5.0.6 on 2024-09-13 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0005_rename_tags_link_image_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="granted_by",
        ),
        migrations.AddField(
            model_name="image",
            name="granted_by_anonym",
            field=models.CharField(
                blank=True,
                default="",
                help_text="E-mail or name of the granted person",
                max_length=255,
                null=True,
                verbose_name="Granted By (Anonym)",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="granted_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="image_granted_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Granted By (User)",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="uploaded_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="image_uploaded_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Uploaded By (User)",
            ),
        ),
    ]
