# Generated by Django 5.0.6 on 2024-09-13 13:39

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0006_remove_image_granted_by_image_granted_by_anonym_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="uploaded_date",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="uploaded date"
            ),
        ),
    ]
