# Generated by Django 5.0.6 on 2024-09-13 13:42

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_image_uploaded_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="uploaded_date",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="image", verbose_name="uploaded date"
            ),
        ),
    ]
