# Generated by Django 5.0.6 on 2024-09-13 13:49

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0008_alter_image_uploaded_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="granted_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Granted Date"),
        ),
        migrations.AlterField(
            model_name="image",
            name="uploaded_date",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="image", verbose_name="Uploaded Date"
            ),
        ),
    ]
