# Generated by Django 5.0.6 on 2024-09-13 14:08

import django.utils.timezone
import server.apps.images.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0009_alter_image_granted_date_alter_image_uploaded_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="granted_date",
            field=server.apps.utils.fields.MonitorFields(
                default=django.utils.timezone.now,
                monitors=["granted_by_anonym", "granted_by_user"],
                verbose_name="Granted Date",
            ),
        ),
    ]
