# Generated by Django 5.0.6 on 2024-09-13 14:21

import server.apps.images.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0011_alter_image_granted_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="granted_date",
        ),
        migrations.AddField(
            model_name="image",
            name="granted_datum",
            field=server.apps.utils.fields.MonitorFields(
                blank=True,
                default=None,
                monitors=["granted_by_anonym", "granted_by_user"],
                null=True,
                verbose_name="Granted Date",
            ),
        ),
    ]
