# Generated by Django 5.0.6 on 2024-09-13 14:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0013_remove_image_granted_datum_image_granted_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagetag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#4B8E43",
                help_text="color as hex number with #",
                image_field=None,
                max_length=18,
                samples=None,
                verbose_name="Color",
            ),
        ),
    ]
