# Generated by Django 5.1.1 on 2024-10-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0014_imagetag_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="review_comment",
            field=models.TextField(blank=True, default="", verbose_name="Review Comment"),
        ),
    ]
