# Generated by Django 5.1.1 on 2024-10-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0015_image_review_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="source_url_raw",
            field=models.URLField(
                blank=True, default="", max_length=500, null=True, verbose_name="Source URL to raw image"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="images", to="images.imagetag", verbose_name="Tags"
            ),
        ),
    ]
