# Generated by Django 5.1.1 on 2024-10-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0016_image_source_url_raw_alter_image_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="height",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Image Height"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="width",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Image Width"),
            preserve_default=False,
        ),
    ]
