# Generated by Django 5.1.1 on 2024-10-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0017_image_height_image_width"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="height",
        ),
        migrations.RemoveField(
            model_name="image",
            name="width",
        ),
        migrations.AlterField(
            model_name="image",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="images", to="images.imagetag", verbose_name="Tags"),
        ),
    ]
