# Generated by Django 5.1.1 on 2024-10-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0018_remove_image_height_remove_image_width_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="source_ident",
            field=models.CharField(
                blank=True, default="", max_length=512, null=True, verbose_name="Source Identification"
            ),
        ),
    ]
