# Generated by Django 5.1.1 on 2024-10-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0019_image_source_ident"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, help_text="Only shown to admin if not active", verbose_name="Active"
            ),
        ),
    ]
