# Generated by Django 5.1.1 on 2024-10-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0020_image_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="capture_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Capture Date"),
        ),
    ]
