# Generated by Django 5.2.9 on 2025-12-31 20:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0021_image_capture_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagetag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#4B8E43",
                help_text="color as hex number with #",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Color",
            ),
        ),
    ]
