# Generated by Django 5.2.9 on 2026-01-04 16:23

import django.utils.timezone
import server.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0022_alter_imagetag_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="created",
            field=server.core.models._AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="modified",
            field=server.core.models._AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="imagetag",
            name="created",
            field=server.core.models._AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="imagetag",
            name="modified",
            field=server.core.models._AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
    ]
