# Generated by Django 5.2.9 on 2026-01-04 16:36

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0023_alter_image_created_alter_image_modified_and_more"),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name="image",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_8c4acfcb",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="faeeaf19cc49253920475a003684003c38372b3c",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_8c4acfcb_f7bff",
                    table="images_image",
                    when="BEFORE",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="imagetag",
            trigger=pgtrigger.compiler.Trigger(
                name="upd_mod_43df27cd",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="NEW.modified = NOW(); RETURN NEW;",
                    hash="7446f8734f22f8397751d11b36e6ea1dc83d61ac",
                    operation="UPDATE",
                    pgid="pgtrigger_upd_mod_43df27cd_5cc82",
                    table="images_imagetag",
                    when="BEFORE",
                ),
            ),
        ),
    ]
