# Generated by Django 6.0.3 on 2026-09-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0024_image_upd_mod_8c4acfcb_imagetag_upd_mod_43df27cd"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="provider_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this image was last refreshed from its external provider (openspec pin-external-images; null = not a pinned external image).",
                null=True,
                verbose_name="Provider Synced At",
            ),
        ),
    ]
