# Generated by Django 6.0.3 on 2026-09-26 20:55

import server.apps.meta_image_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0025_image_provider_synced_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=server.apps.meta_image_field.fields.MetaImageField(
                blank=True,
                help_text="Local image file. Pinned external images have no local file — they are served from the source URL through imagor and can be localized later via 'Download raw'.",
                meta_field="image_meta",
                upload_to="images/",
            ),
        ),
    ]
