# Generated by Django 6.0.3 on 2026-09-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0026_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="caption",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional. Pinned external images default to a cleaned-up file name.",
                max_length=400,
                verbose_name="Caption",
            ),
        ),
    ]
