# Generated by Django 6.0.3 on 2026-09-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0027_alter_image_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="provider_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last refresh from the external provider.",
                null=True,
                verbose_name="Provider Synced At",
            ),
        ),
    ]
