# Generated by Django 6.0.3 on 2026-09-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0028_alter_image_provider_synced_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="phash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="64-bit dHash (hex) of the cached thumbnail — near-duplicates sit within a small Hamming distance.",
                max_length=16,
                null=True,
                verbose_name="Perceptual Hash",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="quality_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                help_text="Technical image quality 0–100 (blur, exposure, contrast, resolution) — computed, not curated.",
                null=True,
                verbose_name="Quality Score",
            ),
        ),
    ]
