# Generated by Django 6.0.3 on 2026-09-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0029_image_phash_image_quality_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="blurhash",
            field=models.CharField(
                blank=True,
                help_text="Compact placeholder encoding (~30 chars) served with the API response so clients can render instant placeholders.",
                max_length=50,
                null=True,
                verbose_name="BlurHash",
            ),
        ),
    ]
