# Generated by Django 6.1.1 on 2026-10-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0030_image_thumbhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='author_url',
            field=models.URLField(blank=True, default='', max_length=1000, null=True, verbose_name='Author URL'),
        ),
        migrations.AlterField(
            model_name='image',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=1000, null=True, verbose_name='Source URL'),
        ),
        migrations.AlterField(
            model_name='image',
            name='source_url_raw',
            field=models.URLField(blank=True, default='', max_length=1000, null=True, verbose_name='Source URL to raw image'),
        ),
    ]
